const PENDING_QUERY_KEY='openbookPendingQuery';let terms=[],book,checks=[],tab='requirements';const app=document.querySelector('#app');
const norm=value=>value.toLowerCase().trim().replace(/[\s_-]+/g,'').replace(/[./]/g,'');const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));const term=id=>terms.find(item=>item.id===id);const name=id=>term(id)?.termKo||id;const context=id=>book.quick_term_context?.[id];
const applyPending=pending=>{if(!pending?.query)return;tab='search';search(pending.query);};
Promise.all([fetch('glossary.json').then(response=>response.json()),fetch('openbook-main-m01.json').then(response=>response.json())]).then(([loadedTerms,loadedBook])=>{terms=loadedTerms;book=loadedBook;chrome.storage.local.get(['m01Checks'],saved=>{checks=saved.m01Checks||[];chrome.storage.session.get([PENDING_QUERY_KEY],pending=>{applyPending(pending[PENDING_QUERY_KEY]);if(!pending[PENDING_QUERY_KEY])render();});});chrome.storage.onChanged.addListener((changes,area)=>{if(area==='session'&&changes[PENDING_QUERY_KEY]?.newValue)applyPending(changes[PENDING_QUERY_KEY].newValue);});});
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{tab=button.dataset.tab;render();});function selectTab(){document.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));}function saveChecks(){chrome.storage.local.set({m01Checks:checks});}function render(){selectTab();if(tab==='requirements')requirements();else if(tab==='search')search('');else checklist();}
function bind(){app.querySelectorAll('[data-check]').forEach(input=>input.onchange=()=>{checks=input.checked?[...new Set([...checks,input.dataset.check])]:checks.filter(id=>id!==input.dataset.check);saveChecks();render();});app.querySelectorAll('[data-term]').forEach(link=>link.onclick=event=>{event.preventDefault();tab='search';search(link.dataset.term);});}
function requirements(){const done=checks.length;app.innerHTML=`<div class="progress"><b>${done} / ${book.requirements.length} 확인</b><i><span style="width:${done/book.requirements.length*100}%"></span></i></div><div class="quick">${book.quick_terms.map(id=>`<a href="#" data-term="${id}">${name(id)}</a>`).join('')}</div>`+book.requirements.map((r,i)=>`<article class="req ${checks.includes(r.id)?'done':''}"><label class="req-heading"><input type="checkbox" data-check="${r.id}" ${checks.includes(r.id)?'checked':''}><b>${String(i+1).padStart(2,'0')}. ${r.title}</b></label><p>${r.requirement_summary}</p><p class="ten-second"><b>10초 확인</b> ${r.quick_check}</p><details><summary>화면·코드·질문 확인</summary><p><b>화면</b> ${r.demo_checks[0]}</p><p><b>코드</b> ${r.code_checks[0]}</p><p><b>질문</b> ${r.peer_questions[0]}</p></details></article>`).join('');bind();}
function find(query){const normalized=norm(query);return terms.map(item=>{const m01=context(item.id),values=[item.termKo,item.termEn,...item.aliases,...(m01?.aliases||[])];const rank=values.some(value=>value.toLowerCase()===query.toLowerCase())?0:values.some(value=>norm(value)===normalized)?1:values.some(value=>norm(value).startsWith(normalized))?2:values.some(value=>norm(value).includes(normalized))?3:9;return {item,rank,m01};}).filter(result=>result.rank<9).sort((a,b)=>a.rank-b.rank||Number(Boolean(b.m01))-Number(Boolean(a.m01))).slice(0,12);}
function detail(item,m01){const related=(item.detailRelatedTerms||[]).filter(id=>term(id));return `<details class="detail"><summary>상세 설명 보기</summary>${item.easyExplanation?`<h3>쉽게 설명하면</h3><p>${esc(item.easyExplanation)}</p>`:''}${item.technicalExplanation?`<h3>정확한 기술 설명</h3><p>${esc(item.technicalExplanation)}</p>`:''}${m01?`<h3>M01에서 어떻게 사용되는가</h3><p>${esc(m01.mission_relevance)}</p>`:''}${item.codeExample?`<h3>코드 또는 사용 예</h3><pre><code>${esc(item.codeExample.replace(/^```[\w-]*\n?|```$/g,''))}</code></pre>`:''}${m01?`<h3>화면에서 확인</h3><p>${esc(m01.screen_check)}</p><h3>코드에서 확인</h3><p>${esc(m01.code_check)}</p>`:''}${item.commonMisconceptions?`<h3>흔한 오해</h3><p>${esc(item.commonMisconceptions)}</p>`:''}${related.length?`<h3>관련 용어</h3><div class="quick">${related.map(id=>`<a href="#" data-term="${id}">${name(id)}</a>`).join('')}</div>`:''}</details>`;}
function search(initial){selectTab();app.innerHTML=`<label class="sr" for="q">용어 검색</label><input id="q" value="${esc(initial)}" placeholder="550개 기술용어를 검색하세요"><p id="hint">예: HTML, localStorage, DOM, fetch, GitHub API</p><div id="results"></div>`;const input=document.querySelector('#q');input.oninput=()=>show(input.value);if(initial)show(initial);function show(value){const output=document.querySelector('#results');if(!value.trim()){output.innerHTML='';return;}const results=find(value);output.innerHTML=results.length?results.map(({item,m01})=>`<article class="result ${m01?'m01-context':''}">${m01?'<p class="context-label">본과정 M01 맥락</p>':''}<b>${item.termKo}</b><small>${item.termEn}</small>${m01?`<p><b>10초 요약</b> ${esc(m01.quick_explanation)}</p><p><em>M01에서는</em> ${esc(m01.mission_relevance)}</p><p><b>동료 질문</b> ${esc(m01.peer_question)}</p>`:`<p>${esc(item.summary||'기본 설명을 준비하고 있습니다.')}</p><em>전체 사전 용어</em>`}${item.hasDetailedContent?detail(item,m01):'<p class="detail-pending">상세 설명 준비 중</p>'}</article>`).join(''):`<article class="unknown"><b>${esc(value)}</b><p>아직 코디세이 오픈북 사전에 없는 용어입니다.</p><button id="websearch">웹에서 검색하기</button></article>`;bind();if(!results.length)document.querySelector('#websearch').onclick=()=>chrome.search.query({text:value,disposition:'NEW_TAB'});}}
function checklist(){app.innerHTML='<h2>평가 체크</h2>'+book.requirements.map(r=>`<label class="check"><input type="checkbox" data-check="${r.id}" ${checks.includes(r.id)?'checked':''}><span>${r.title}</span></label>`).join('')+'<button class="reset" id="reset">평가 체크 초기화</button>';document.querySelector('#reset').onclick=()=>{checks=[];saveChecks();checklist();};bind();}
