#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build Wave 3's final field maps and narrowly useful cross-field overlays."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TERMS = {x["id"]: x for x in json.loads((ROOT / "data/curated/glossary-master-v0.1.yaml").read_text(encoding="utf-8"))["terms"]}
CLASS = {x["termId"]: x for x in json.loads((ROOT / "data/knowledge-maps/atlas/term-field-classification.json").read_text(encoding="utf-8"))["classifications"]}
DOCS = "https://redis.io/docs/latest/"
RFC = "https://www.rfc-editor.org/"
AI_DOCS = "https://platform.openai.com/docs/"

def n(term_id, region, role="core", summary=None):
    item = TERMS[term_id]
    value = {"id":f"term:{term_id}","termId":term_id,"label":item["term_en"],"labelKo":item["term_ko"],"nodeOrigin":"field","nodeRole":role,"layer":region,"primaryRegion":region,"summary":summary or f"{item['term_ko']}({item['term_en']})를 이 기술 분야의 맥락에서 살펴보는 canonical 용어."}
    if role == "foundation": value["foundationRationale"] = "이 지도에서 핵심 구조와 선택 기준을 연결하는 기반 개념이다."
    return value

def e(a, relation, b, reason, source, confidence="HIGH", evidence="official-documentation"):
    return {"from":f"term:{a}","relation":relation,"to":f"term:{b}","reason":reason,"confidence":confidence,"evidenceType":evidence,"source":source}

def regions(*items):
    return [{"id":i,"label":l,"description":d,"layout":{"x":24+(index%3)*416,"y":38+(index//3)*245,"width":390 if index%3<2 else 404,"height":220,"columns":3}} for index,(i,l,d) in enumerate(items)]

def graph(map_id, field_id, title, description, region_data, routes, nodes, edges):
    for item in nodes:
        c=CLASS[item["termId"]]
        assert field_id in [c["primaryField"],*c["secondaryFields"]], f"{map_id}: {item['termId']} outside field"
    return {"schemaVersion":"1.0","artifactType":"authored-field-knowledge-graph","mapId":map_id,"fieldId":field_id,"title":title,"description":description,"status":"implemented","canvasHeight":760,"regions":region_data,"relationOntology":{"is_a":"종류 또는 구체적 형태다.","based_on":"이해 또는 동작이 기반을 둔다.","uses":"사용하거나 소비한다.","interacts_with":"동작상 상호작용한다.","prerequisite":"먼저 이해하면 좋다.","provided_by":"환경 또는 계층이 제공한다.","compare_with":"차이와 선택 기준을 비교한다."},"learningRoutes":routes,"nodes":nodes,"edges":edges}

def overlay(map_id, mission_id, terms, routes, description=None):
    prefix="본과정" if mission_id.startswith("main-") else "예비"
    mission=mission_id.split("-",1)[1].upper()
    return {"overlayId":f"{map_id}-{mission_id}","mapId":map_id,"missionId":mission_id,"label":f"{prefix} {mission} 관련 기술","description":description or f"{prefix} {mission}의 해당 Field Map 맥락을 강조한다.","nodeIds":[f"term:{i}" for i,_,_ in terms],"edgeIds":[],"routeIds":routes,"nodeRefs":[{"nodeId":f"term:{i}","termId":i,"missionContext":c,"relation":r,"routeIds":routes} for i,c,r in terms]}

def write_map(payload, overlays):
    path=ROOT / "data/knowledge-maps" / payload["mapId"]
    (path / "overlays").mkdir(parents=True,exist_ok=True)
    (path / "knowledge-map.json").write_text(json.dumps(payload,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    for item in overlays: (path / "overlays" / f"{item['missionId']}.json").write_text(json.dumps(item,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")

def extend_data_map():
    """Add file/data-processing nodes needed by M03 without pretending it is relational DB work."""
    path=ROOT / "data/knowledge-maps/data-database/knowledge-map.json"; data=json.loads(path.read_text(encoding="utf-8"))
    existing={x["termId"] for x in data["nodes"] if x.get("termId")}
    additions=[n("data-json","data-exchange","boundary","data.json은 구조화된 데이터를 교환·입력 artifact로 담는 파일이다."),n("filter","data-exchange","core","조건에 맞는 data item만 남기는 data processing operation."),n("csv","data-exchange","core","행과 열 형태의 데이터를 텍스트로 교환하는 comma-separated values format."),n("json-lines","data-exchange","core","각 줄이 하나의 JSON value인 streaming-friendly text format."),n("serialization","data-exchange","foundation","in-memory data를 저장·전송 가능한 representation으로 바꾸는 과정."),n("streaming","data-exchange","foundation","전체 데이터를 한 번에 적재하지 않고 순차적으로 처리하는 방식.")]
    if "data-exchange" not in {x["id"] for x in data["regions"]}: data["regions"].append({"id":"data-exchange","label":"Data Exchange","description":"파일 형식과 순차 data processing.","layout":{"x":24,"y":570,"width":1232,"height":180,"columns":6}})
    data["nodes"].extend(x for x in additions if x["termId"] not in existing)
    known={(x["from"],x["relation"],x["to"]) for x in data["edges"]}
    additions_edges=[e("serialization","interacts_with","data-json","serialization은 data를 JSON representation으로 만들 수 있다.",RFC),e("filter","uses","data-json","data.json input에 filtering operation을 적용할 수 있다.",RFC,"MEDIUM","architectural-inference"),e("csv","compare_with","json-lines","CSV와 JSON Lines는 tabular/structured streaming data exchange 선택지다.",RFC,"MEDIUM","architectural-inference"),e("streaming","uses","json-lines","JSON Lines는 record를 순차 처리하는 streaming pipeline에 적합할 수 있다.",RFC,"MEDIUM","architectural-inference"),e("streaming","interacts_with","serialization","streaming pipeline은 serialized record를 순차 처리한다.",RFC,"MEDIUM","architectural-inference")]
    data["edges"].extend(x for x in additions_edges if (x["from"],x["relation"],x["to"]) not in known)
    route={"id":"file-data-processing","label":"파일 데이터를 처리하는 길","description":"CSV·JSON Lines 같은 serialized data를 filter와 streaming 방식으로 처리한다.","nodeIds":["term:serialization","term:csv","term:json-lines","term:filter","term:streaming"],"scope":"field"}
    if route["id"] not in {x["id"] for x in data["learningRoutes"]}: data["learningRoutes"].append(route)
    path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")

def build():
    algorithms_nodes=[
        n("hash-function","hash-lookup","foundation","입력을 고정 범위 value로 변환하는 function; hash map 자체와 같지 않다."),n("hash-map","hash-lookup","core","key를 hash로 bucket에 배치해 lookup을 지원하는 associative data structure."),n("hash-bucket","hash-lookup","core","hash map에서 같은 index로 모인 entry를 담는 storage slot."),n("collision","hash-lookup","foundation","서로 다른 key가 같은 hash bucket으로 향하는 상황."),n("separate-chaining","hash-lookup","core","collision bucket에 여러 entry를 연결해 저장하는 collision resolution strategy."),n("load-factor","hash-lookup","foundation","hash map의 entry 수와 bucket 수 비율로, collision/resize 판단과 관련된다."),n("o-constant-time","hash-lookup","foundation","평균적인 hash lookup 분석에서 자주 목표로 삼는 O(1) growth bound; 실제 초 단위가 아니다."),
        n("stack","linear-structures","core","last-in first-out access discipline의 linear data structure; call stack 전체와 동일하지 않다."),n("queue","linear-structures","core","first-in first-out access discipline의 linear data structure; event loop와 동의어가 아니다."),n("deque","linear-structures","core","양 끝에서 insertion/removal을 지원하는 double-ended queue."),
        n("binary-search-tree","trees-heaps","core","ordered key를 left/right subtree 규칙으로 조직하는 tree structure."),n("min-heap","trees-heaps","core","최솟값을 빠르게 꺼내기 위한 heap property를 유지하는 tree-based structure."),n("heap-property","trees-heaps","foundation","parent와 child value 사이에 유지하는 heap ordering invariant."),
        n("directed-graph","graphs-dag","core","edge에 direction이 있는 graph; tree와 일반 graph를 동일시하지 않는다."),n("directed-acyclic-graph","graphs-dag","core","방향이 있고 cycle이 없는 graph(DAG)."),n("cycle","graphs-dag","foundation","graph path가 출발 node로 다시 돌아오는 구조; DAG에는 존재할 수 없다."),n("commit-node","graphs-dag","boundary","Git commit은 DAG concept를 적용해 볼 수 있는 application node이며 Algorithms의 core는 아니다."),n("parent-commit","graphs-dag","boundary","Git history에서 commit을 이전 parent commit과 잇는 application relation."),
        n("graph-traversal","traversal-order","foundation","graph node와 edge를 규칙에 따라 방문하는 strategy 범주."),n("bfs","traversal-order","core","가까운 level부터 방문하는 breadth-first traversal/search strategy."),n("dfs","traversal-order","core","한 path를 깊게 따라간 뒤 되돌아오는 depth-first traversal/search strategy."),n("topological-sort","traversal-order","core","DAG의 directed dependency를 만족하는 linear order를 만드는 algorithm."),n("topological-order","traversal-order","core","topological sort가 만든 valid linear order."),n("time-complexity","complexity","foundation","input size에 따라 resource use가 어떻게 성장하는지 분석하는 기준."),n("amortized-complexity","complexity","core","일련의 operation 전체 비용을 평균화해 분석하는 방법."),n("redis","applied-structures","boundary","Redis는 abstract data structure가 아니라 여러 자료구조를 제공하는 data store."),n("cache-eviction","applied-structures","core","cache capacity가 찼을 때 entry를 제거하는 policy."),n("least-recently-used","applied-structures","core","최근 가장 오래 사용되지 않은 entry를 제거하는 cache eviction policy."),
    ]
    algo_routes=[
        {"id":"fast-lookup","label":"빠르게 찾는 길","description":"hash function, bucket, collision strategy와 load factor가 hash map lookup 구조를 만든다.","nodeIds":["term:hash-function","term:hash-map","term:hash-bucket","term:separate-chaining","term:o-constant-time"],"scope":"field"},
        {"id":"follow-history","label":"관계를 따라가는 길","description":"directed graph에서 cycle 없는 DAG를 만들고 traversal/order로 관계를 따라간다.","nodeIds":["term:directed-graph","term:directed-acyclic-graph","term:cycle","term:graph-traversal","term:topological-sort","term:topological-order"],"scope":"field"},
        {"id":"explore-graph","label":"그래프를 탐색하는 길","description":"BFS와 DFS는 graph traversal/search strategy이며 graph 자체나 queue/stack의 동의어가 아니다.","nodeIds":["term:graph-traversal","term:bfs","term:dfs"],"scope":"field"},
        {"id":"judge-growth","label":"효율을 판단하는 길","description":"time complexity와 amortized complexity는 input size에 따른 growth를 비교한다.","nodeIds":["term:time-complexity","term:o-constant-time","term:amortized-complexity"],"scope":"field"},
    ]
    algorithms=graph("algorithms-data-structures","algorithms-data-structures","Algorithms / Data Structures","lookup, graph traversal, complexity와 applied structure가 어떻게 연결되는지 살펴봅니다.",regions(("hash-lookup","Hash / Lookup","key 기반 빠른 조회."),("linear-structures","Linear Structures","stack, queue, deque."),("trees-heaps","Trees / Heaps","ordered tree와 heap invariant."),("graphs-dag","Graphs / DAG","방향, cycle, history context."),("traversal-order","Traversal","방문 전략과 ordering."),("complexity","Complexity","입력 크기에 따른 growth."),("applied-structures","Applied Structures","Redis와 cache policy.")),algo_routes,algorithms_nodes,[
        e("hash-map","uses","hash-function","hash map은 key를 bucket index로 정하기 위해 hash function을 사용한다.",DOCS),e("hash-bucket","provided_by","hash-map","hash map은 entry를 bucket에 배치한다.",DOCS),e("collision","interacts_with","hash-bucket","collision은 같은 bucket으로 향한 key들에서 발생한다.",DOCS),e("separate-chaining","uses","collision","separate chaining은 collision entry를 bucket 안에서 관리한다.",DOCS),e("load-factor","interacts_with","hash-map","load factor는 hash map collision/resize tradeoff와 관계된다.",DOCS),e("o-constant-time","based_on","hash-map","O(1)은 적절한 가정 아래 hash map lookup의 growth 분석이다.",DOCS,"MEDIUM","architectural-inference"),e("deque","compare_with","queue","deque는 양 끝 접근을 제공하고 queue는 FIFO discipline을 강조한다.",DOCS),e("stack","compare_with","queue","stack의 LIFO discipline은 queue의 FIFO discipline과 다르다.",DOCS),e("binary-search-tree","compare_with","min-heap","BST와 min heap은 모두 tree-based structure지만 ordering goal이 다르다.",DOCS),e("min-heap","based_on","heap-property","min heap은 heap property를 유지한다.",DOCS),e("directed-acyclic-graph","is_a","directed-graph","DAG는 directed graph의 한 종류다.",DOCS),e("directed-acyclic-graph","compare_with","cycle","DAG에는 directed cycle이 없어야 한다.",DOCS),e("commit-node","interacts_with","directed-acyclic-graph","Git commit node는 DAG application context로 이해할 수 있다.",DOCS,"MEDIUM","architectural-inference"),e("parent-commit","interacts_with","commit-node","parent relation은 commit history graph의 edge를 표현한다.",DOCS,"MEDIUM","architectural-inference"),e("graph-traversal","uses","directed-graph","traversal은 graph node와 edge를 방문한다.",DOCS),e("bfs","is_a","graph-traversal","BFS는 graph traversal strategy다.",DOCS),e("dfs","is_a","graph-traversal","DFS는 graph traversal strategy다.",DOCS),e("topological-sort","uses","directed-acyclic-graph","topological sort는 DAG에 적용된다.",DOCS),e("topological-order","provided_by","topological-sort","topological sort 결과는 valid topological order다.",DOCS),e("amortized-complexity","based_on","time-complexity","amortized analysis는 operation sequence의 time complexity를 분석한다.",DOCS),e("least-recently-used","is_a","cache-eviction","LRU는 cache eviction policy다.",DOCS),e("redis","interacts_with","hash-map","Redis hash 같은 data type은 hash-map concept의 applied storage context다.",DOCS,"MEDIUM","architectural-inference"),e("cache-eviction","interacts_with","redis","Redis memory policy는 cache eviction context를 가질 수 있다.",DOCS),
    ])
    algo_overlays=[overlay("algorithms-data-structures","main-m09",[("hash-function","key를 hash value로 변환한다.","required"),("hash-map","빠른 key lookup 구조를 구현한다.","direct"),("hash-bucket","bucket storage를 이해한다.","direct"),("collision","hash collision을 처리한다.","required"),("separate-chaining","collision resolution을 구현한다.","direct"),("load-factor","hash table 상태를 관찰한다.","direct"),("o-constant-time","lookup growth 목표를 이해한다.","direct"),("redis","자료구조를 제공하는 applied data store를 사용한다.","direct"),("cache-eviction","memory pressure에서 eviction을 다룬다.","required"),("least-recently-used","LRU policy를 구현한다.","direct"),("queue","publish/subscribe message queue 맥락을 확장한다.","direct"),("min-heap","Top N structure를 이해한다.","direct")],["fast-lookup","judge-growth"],"Redis를 추상 자료구조와 구분하며 빠른 lookup과 cache policy를 강조한다."),overlay("algorithms-data-structures","main-m10",[("directed-graph","history relation의 directed structure를 이해한다.","required"),("directed-acyclic-graph","commit history DAG를 구현한다.","direct"),("cycle","history graph가 cycle을 만들지 않게 검증한다.","required"),("commit-node","Git-like commit을 graph application node로 다룬다.","direct"),("parent-commit","parent relation을 연결한다.","direct"),("graph-traversal","history를 따라 방문한다.","direct"),("bfs","ancestor search strategy를 비교한다.","required"),("dfs","history traversal strategy를 비교한다.","required"),("topological-sort","dependency-respecting order를 확장한다.","related"),("topological-order","정렬 결과를 이해한다.","direct")],["follow-history","explore-graph"],"Git 자체가 아니라 Git-like history에 쓰이는 DAG와 traversal application context를 강조한다.")]
    write_map(algorithms,algo_overlays)

    ai_nodes=[
        n("ai-api","request-interface","core","AI model/service에 request를 보내는 access interface이며 AI 자체가 아니다."),n("rest-api","request-interface","boundary","AI API가 HTTP interface를 노출할 수 있는 API design context."),n("http-request","request-interface","boundary","AI API endpoint에 보내는 network request."),n("api-key","request-interface","shared","service access credential로, end-user authentication token과 같은 뜻이 아니다."),n("prompt-design","prompt-output","core","model이 수행할 task와 context를 명확히 전달하도록 prompt를 설계하는 practice."),n("prompt-template","prompt-output","core","반복 task에 variable을 채워 넣어 쓸 수 있는 reusable prompt structure."),n("ai-model","model-inference","core","input을 output으로 변환하도록 학습된 parameterized model; API와 같은 것이 아니다."),n("inference","model-inference","core","학습된 model에 input을 적용해 output을 계산하는 단계로 training과 구분된다."),n("temperature","model-inference","core","sampling output 다양성에 영향을 주는 generation parameter."),n("max-tokens","model-inference","core","한 response에서 생성할 token의 상한 설정."),n("token-usage-cost","model-inference","core","input/output token usage와 service cost를 관찰하는 운영 metric; authentication token과 무관하다."),
        n("structured-output","prompt-output","core","정해진 schema/format에 맞춰 model output을 만들도록 요청하는 방식."),n("post-processing","prompt-output","core","model output을 application에 쓰기 전 format·sanitize·transform하는 후처리."),n("output-validation","prompt-output","core","output이 expected structure/constraints를 만족하는지 확인하며 사실성을 보장하지는 않는다."),n("regeneration","prompt-output","core","unsuitable output에 대해 prompt/parameter를 조정해 다시 generation을 요청하는 흐름."),n("human-in-the-loop","prompt-output","core","사람의 review/approval를 workflow에 넣어 automated output을 보완하는 방식."),
        n("tensor","model-compute","core","다차원 numerical data representation으로 model computation의 기본 unit."),n("weight","model-compute","core","model이 learned relationship을 encode하는 parameter."),n("attention","model-compute","core","input representation 사이의 relevance를 가중해 계산하는 mechanism."),n("neural-processing-unit","model-compute","core","neural-network workloads를 효율화하도록 설계된 processor."),n("gpu-vs-npu","model-compute","core","GPU와 NPU는 architecture와 workload tradeoff가 다르며 하나가 모든 AI 실행에 필수는 아니다."),n("mac-operation","model-compute","core","multiply-accumulate numerical operation으로 neural computation의 한 building block."),
    ]
    ai_routes=[
        {"id":"ai-request","label":"AI 요청이 처리되는 길","description":"prompt template이 AI API request로 model inference를 거쳐 output validation과 human review로 이어진다.","nodeIds":["term:prompt-template","term:prompt-design","term:ai-api","term:ai-model","term:inference","term:structured-output","term:output-validation","term:human-in-the-loop"],"scope":"field"},
        {"id":"understand-model","label":"모델을 이해하는 길","description":"AI model은 learned weight와 attention 같은 computation으로 inference를 수행한다.","nodeIds":["term:ai-model","term:weight","term:attention","term:inference"],"scope":"field"},
        {"id":"compute-choice","label":"AI 연산을 실행하는 길","description":"tensor와 MAC operation workload는 GPU/NPU architecture choice와 연결되지만 NPU가 모든 AI에 필요하지는 않다.","nodeIds":["term:tensor","term:mac-operation","term:neural-processing-unit","term:gpu-vs-npu"],"scope":"field"},
    ]
    ai=graph("ai-ml-computing","ai-ml-computing","AI / ML / Computing","AI service request, model inference, output review, compute concepts를 구분해 살펴봅니다.",regions(("request-interface","Request / Interface","service access와 network boundary."),("prompt-output","Prompt / Output","instruction, format, review."),("model-inference","Model / Inference","model execution과 generation control."),("model-compute","Model Compute","tensor, parameter, accelerator.")),ai_routes,ai_nodes,[
        e("ai-api","uses","http-request","AI API는 HTTP request interface로 호출될 수 있다.",AI_DOCS),e("rest-api","interacts_with","ai-api","AI service API는 REST-style HTTP interface를 제공할 수 있다.",AI_DOCS,"MEDIUM","architectural-inference"),e("api-key","interacts_with","ai-api","API key는 service request authentication/authorization에 쓰일 수 있다.",AI_DOCS),e("prompt-template","uses","prompt-design","template은 prompt design 원칙을 reusable structure로 적용한다.",AI_DOCS),e("prompt-design","interacts_with","ai-model","prompt는 model inference에 전달될 input instruction을 구성한다.",AI_DOCS),e("ai-api","provided_by","ai-model","AI API는 model/service inference access를 제공할 수 있다.",AI_DOCS),e("inference","uses","ai-model","inference는 trained model에 input을 적용한다.",AI_DOCS),e("temperature","interacts_with","inference","temperature는 sampling-based inference output에 영향을 준다.",AI_DOCS),e("max-tokens","interacts_with","inference","max tokens는 generation output length 상한을 설정한다.",AI_DOCS),e("token-usage-cost","interacts_with","ai-api","token usage는 API consumption cost/limit 관찰에 쓰인다.",AI_DOCS),e("structured-output","uses","prompt-design","structured output request는 prompt/API format constraints를 사용한다.",AI_DOCS),e("post-processing","interacts_with","structured-output","post-processing은 structured output을 application format으로 다듬을 수 있다.",AI_DOCS),e("output-validation","interacts_with","structured-output","validation은 output structure와 constraints를 검사한다.",AI_DOCS),e("regeneration","interacts_with","output-validation","failed validation 뒤 regeneration을 요청할 수 있다.",AI_DOCS,"MEDIUM","architectural-inference"),e("human-in-the-loop","interacts_with","output-validation","human review는 automated validation을 보완한다.",AI_DOCS),e("weight","based_on","ai-model","model은 learned weight parameter를 포함한다.",AI_DOCS),e("attention","interacts_with","ai-model","attention은 일부 model architecture에서 input relevance를 계산한다.",AI_DOCS,"MEDIUM","architectural-inference"),e("tensor","uses","mac-operation","tensor computation은 MAC 같은 numerical operation을 수행한다.",AI_DOCS),e("neural-processing-unit","interacts_with","tensor","NPU는 tensor/neural computation workload를 가속할 수 있다.",AI_DOCS),e("gpu-vs-npu","compare_with","neural-processing-unit","GPU와 NPU choice는 architecture/workload tradeoff를 비교한다.",AI_DOCS),
    ])
    ai_overlays=[overlay("ai-ml-computing","main-m06",[("ai-api","AI service endpoint를 호출한다.","direct"),("ai-model","코드 설명을 만드는 model context를 이해한다.","direct"),("api-key","service credential을 안전하게 다룬다.","direct"),("http-request","API request boundary를 이해한다.","required"),("prompt-design","코드 설명 요청을 설계한다.","direct"),("prompt-template","reusable instruction template을 만든다.","required"),("temperature","generation parameter를 조정한다.","direct"),("max-tokens","response length를 제어한다.","direct"),("structured-output","application-friendly output format을 다룬다.","related"),("post-processing","AI output을 application에 맞게 다듬는다.","direct"),("output-validation","output structure를 검증한다.","direct"),("regeneration","불충분한 output을 다시 생성한다.","direct"),("human-in-the-loop","사람이 최종 결과를 검토한다.","required"),("token-usage-cost","usage/cost context를 확인한다.","related")],["ai-request","understand-model"],"AI API, prompt, model inference와 output review를 중심으로 M06 도우미 흐름을 강조한다."),overlay("ai-ml-computing","preliminary-m03",[("tensor","matrix/tensor representation을 확장한다.","related"),("neural-processing-unit","NPU simulation context를 다룬다.","direct"),("gpu-vs-npu","GPU/NPU tradeoff를 비교한다.","related"),("mac-operation","neural numeric operation을 구현한다.","direct"),("attention","attention concept를 확장한다.","related"),("inference","model inference context를 연결한다.","related")],["compute-choice","understand-model"],"예비 M03의 programming/data 중심 작업에서 의미 있는 AI computing 부분만 부분 강조한다.")]
    write_map(ai,ai_overlays)
    extend_data_map()

if __name__ == "__main__": build()
