#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the authored Wave 2 field-map graphs and mission overlays.

The compact declarations below are the source of truth.  JSON is emitted beside
the Wave 1 maps so the registry, validator, and web-data builder all consume
the same contract.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GLOSSARY = {item["id"]: item for item in json.loads((ROOT / "data/curated/glossary-master-v0.1.yaml").read_text(encoding="utf-8"))["terms"]}
CLASSIFICATIONS = {item["termId"]: item for item in json.loads((ROOT / "data/knowledge-maps/atlas/term-field-classification.json").read_text(encoding="utf-8"))["classifications"]}

DOC = "https://docs.docker.com/"
LINUX = "https://www.kernel.org/doc/html/latest/"
RFC = "https://www.rfc-editor.org/"
FASTAPI = "https://fastapi.tiangolo.com/"
OWASP = "https://cheatsheetseries.owasp.org/"

def node(term_id, region, role="core", summary=None, layer=None):
    term = GLOSSARY[term_id]
    return {
        "id": f"term:{term_id}", "termId": term_id, "label": term["term_en"], "labelKo": term["term_ko"],
        "nodeOrigin": "field", "nodeRole": role, "layer": layer or region, "primaryRegion": region,
        "summary": summary or f"{term['term_ko']}({term['term_en']})를 이 분야의 맥락에서 살펴보는 canonical 용어.",
        **({"foundationRationale": "이 지도에서 핵심 개념 사이의 전제와 구분을 설명한다."} if role == "foundation" else {}),
    }

def edge(a, rel, b, reason, source, confidence="HIGH", evidence="official-documentation"):
    return {"from": f"term:{a}", "relation": rel, "to": f"term:{b}", "reason": reason, "confidence": confidence, "evidenceType": evidence, "source": source}

def overlay(map_id, mission_id, label, description, terms, routes):
    return {"overlayId": f"{map_id}-{mission_id}", "mapId": map_id, "missionId": mission_id, "label": label,
            "description": description, "nodeIds": [f"term:{term_id}" for term_id, _, _ in terms], "routeIds": routes,
            "nodeRefs": [{"nodeId": f"term:{term_id}", "termId": term_id, "missionContext": context, "relation": relation, "routeIds": routes} for term_id, context, relation in terms]}

def graph(map_id, field_id, title, description, regions, routes, nodes, edges):
    compatible = [node["termId"] for node in nodes]
    for term_id in compatible:
        item = CLASSIFICATIONS[term_id]
        assert field_id in [item["primaryField"], *item["secondaryFields"]], f"{map_id}: {term_id} not available in {field_id}"
    return {"schemaVersion": "1.0", "artifactType": "authored-field-knowledge-graph", "mapId": map_id, "fieldId": field_id,
            "title": title, "description": description, "status": "implemented", "canvasHeight": 760,
            "regions": regions, "relationOntology": {"is_a":"종류 또는 구체적 형태다.", "based_on":"이해 또는 동작이 기반을 둔다.", "uses":"사용하거나 소비한다.", "interacts_with":"동작상 상호작용한다.", "prerequisite":"먼저 이해하면 좋다.", "provided_by":"환경 또는 계층이 제공한다.", "compare_with":"차이와 선택 기준을 비교한다."},
            "learningRoutes": routes, "nodes": nodes, "edges": edges}

def regions(*items):
    width, height = 390, 220
    return [{"id": ident, "label": label, "description": description, "layout": {"x": 24 + (i % 3) * 416, "y": 38 + (i // 3) * 245, "width": width if i % 3 < 2 else 404, "height": height, "columns": 3}} for i, (ident, label, description) in enumerate(items)]

def build():
    maps = {}
    overlays = {}

    linux_nodes = [
        node("linux", "kernel-runtime", summary="커널과 사용자 공간을 포함해 프로세스와 파일을 운영하는 운영체제."), node("kernel", "kernel-runtime", "foundation", "하드웨어 자원 접근과 핵심 운영체제 서비스를 맡는 특권 실행 계층."), node("shell", "kernel-runtime", summary="명령을 해석해 프로그램 실행을 요청하는 인터페이스이며 terminal 창 자체가 아니다."), node("environment-variable", "kernel-runtime", "shared", "프로세스에 전달되는 이름-값 설정이며 배포 비밀값의 저장소 자체는 아니다."),
        node("process", "process-thread", summary="실행 중인 프로그램 인스턴스로, 독립된 주소 공간과 자원을 가진다."), node("process-id", "process-thread", summary="운영체제가 현재 프로세스를 식별하는 숫자이며 프로세스의 모든 정체성을 뜻하지는 않는다."), node("thread", "process-thread", "foundation", "한 프로세스 안에서 실행 흐름을 나누는 단위로, process와 같지 않다."), node("scheduler", "process-thread", "foundation", "실행 가능한 작업에 CPU 시간을 배분하는 운영체제 정책과 기구."),
        node("cpu-usage", "resources", summary="관측 구간에 CPU가 사용된 정도다. load average와 같은 값이 아니다."), node("memory-usage", "resources", summary="프로세스나 시스템이 실제 메모리를 사용하는 관측값이다."), node("out-of-memory", "resources", summary="메모리 압박으로 시스템이 할당을 거절하거나 작업을 종료하는 상태."), node("resource-exhaustion", "resources", "foundation", "CPU·메모리·파일 기술자 등 유한 자원이 고갈되는 문제 범주."),
        node("filesystem", "files-permissions", "foundation", "파일과 디렉터리를 이름·경로·권한으로 조직하는 계층."), node("file-io", "files-permissions", summary="프로그램이 파일을 읽고 쓰는 입출력 작업이다."), node("directory", "files-permissions", summary="filesystem 안에서 이름과 경로로 파일을 조직하는 container 객체."),
        node("systemd", "services-observation", summary="Linux에서 서비스를 초기화·관리하는 system and service manager."), node("process-monitoring", "services-observation", summary="실행 중인 프로세스의 상태와 자원을 관찰하는 작업."), node("ps", "services-observation", summary="process 자체가 아니라 process 정보를 조회하는 명령이다."), node("top", "services-observation", summary="실시간에 가까운 process와 resource 사용량을 표시하는 관찰 도구."), node("monitor-sh", "services-observation", summary="시스템 상태를 반복 확인하도록 작성한 monitoring shell script."),
    ]
    linux_routes = [
        {"id":"program-to-cpu","label":"프로그램이 실행되는 길","description":"셸이 실행을 요청하면 process가 생기고 scheduler가 CPU 시간을 배분한다.","nodeIds":["term:shell","term:process","term:process-id","term:scheduler","term:cpu-usage"],"scope":"field"},
        {"id":"diagnose-pressure","label":"문제를 찾는 길","description":"process 관찰에서 CPU·memory 사용량, monitoring 기록과 자원 고갈 징후를 함께 확인한다.","nodeIds":["term:process-monitoring","term:cpu-usage","term:memory-usage","term:resource-exhaustion","term:monitor-sh"],"scope":"field"},
        {"id":"service-lifecycle","label":"서비스가 살아있는 길","description":"systemd가 관리하는 process를 관찰하고 monitoring script로 상태를 확인한다.","nodeIds":["term:systemd","term:process","term:process-monitoring","term:monitor-sh"],"scope":"field"},
    ]
    maps["linux-runtime"] = graph("linux-runtime", "systems-runtime", "Linux / OS / Runtime", "프로세스, 자원, 파일, 서비스가 Linux 운영체제 위에서 어떻게 연결되는지 살펴봅니다.", regions(("kernel-runtime","Kernel / Runtime","운영체제 계층과 실행 환경."),("process-thread","Process / Thread","실행 단위와 CPU 배분."),("resources","Resources","CPU와 메모리의 관찰."),("files-permissions","Files","파일 시스템과 접근 규칙."),("services-observation","Services / Observation","서비스 상태와 진단.")), linux_routes, linux_nodes, [
        edge("linux","uses","kernel","Linux는 kernel을 중심으로 user-space 도구와 운영체제 환경을 구성한다.",LINUX), edge("shell","uses","process","셸은 명령으로 process 실행을 요청한다.",LINUX), edge("process","provided_by","kernel","프로세스의 핵심 관리 기능은 kernel이 제공한다.",LINUX), edge("process-id","is_a","process","PID는 process 자체가 아니라 process에 부여된 식별자다.",LINUX), edge("thread","based_on","process","thread는 process의 주소 공간과 자원을 공유할 수 있다.",LINUX), edge("scheduler","interacts_with","thread","scheduler는 실행 가능한 thread에 CPU 시간을 배분한다.",LINUX), edge("cpu-usage","interacts_with","scheduler","CPU 사용량은 scheduler가 배분한 실행의 관측 결과다.",LINUX), edge("memory-usage","interacts_with","process","memory 사용량은 process 단위로 관찰할 수 있다.",LINUX), edge("out-of-memory","is_a","resource-exhaustion","OOM은 메모리 자원 고갈의 한 결과다.",LINUX), edge("file-io","uses","filesystem","파일 I/O는 filesystem이 제공하는 경로와 객체를 사용한다.",LINUX), edge("directory","interacts_with","filesystem","directory는 filesystem 안에서 이름과 경로를 조직한다.",LINUX), edge("systemd","interacts_with","process","systemd는 service process의 생명주기를 관리한다.",LINUX), edge("process-monitoring","uses","ps","ps는 process 정보를 조회하는 관찰 도구다.",LINUX), edge("top","uses","cpu-usage","top은 CPU 사용량을 포함한 상태를 표시한다.",LINUX), edge("monitor-sh","interacts_with","process-monitoring","monitoring script는 관찰값을 모아 진단 근거를 만든다.",LINUX), edge("environment-variable","provided_by","process","환경 변수는 process 실행 환경에 전달된다.",LINUX),
    ])
    overlays["linux-runtime"] = [
        overlay("linux-runtime","main-m07","본과정 M07 관련 기술","시스템 상태 점검과 서비스 운영에 필요한 관찰 지점을 강조합니다.",[("linux","호스트 운영체제의 기본 환경","direct"),("process-monitoring","실행 상태를 점검한다.","direct"),("cpu-usage","CPU 임계치를 관찰한다.","direct"),("memory-usage","메모리 상태를 점검한다.","direct"),("systemd","서비스 상태 문맥을 연결한다.","related"),("monitor-sh","점검 근거를 남긴다.","direct"),("filesystem","서비스 파일을 관찰하는 기반이다.","related")],["diagnose-pressure","service-lifecycle"]),
        overlay("linux-runtime","main-m08","본과정 M08 관련 기술","성능 저하와 멈춤의 원인을 process·thread·자원 관점에서 강조합니다.",[("process","문제 재현 대상의 실행 단위다.","direct"),("process-id","문제 process를 식별한다.","direct"),("thread","동시 실행과 교착 상태를 구분한다.","direct"),("scheduler","스케줄링 정책을 비교한다.","related"),("cpu-usage","CPU spike를 관찰한다.","direct"),("memory-usage","메모리 압박을 확인한다.","direct"),("out-of-memory","메모리 고갈 결과를 분석한다.","direct"),("resource-exhaustion","근본 원인 범주를 찾는다.","required"),("ps","process 정보를 조회한다.","direct"),("top","자원 사용을 관찰한다.","direct"),("monitor-sh","증거 기록을 남긴다.","direct")],["program-to-cpu","diagnose-pressure"]),
    ]

    devops_nodes = [
        node("docker", "build-image", summary="컨테이너 image를 만들고 실행하는 도구 생태계이며 container 일반 개념 전체와 같지 않다."), node("dockerfile", "build-image", summary="image를 만들기 위한 재현 가능한 build instructions 파일."), node("base-image", "build-image", "foundation", "새 image가 시작하는 기존 image 계층."), node("docker-image", "build-image", summary="실행에 필요한 filesystem과 metadata를 담은 불변에 가까운 배포 artifact."), node("layer", "build-image", "foundation", "image build 단계에서 재사용 가능한 filesystem 변경 단위."),
        node("docker-container", "runtime", summary="image에서 생성되어 실행되는 격리된 process 환경이며 virtual machine과 같지 않다."), node("containerd-runc", "runtime", "foundation", "container 실행을 지원하는 runtime 구성요소."), node("environment-variable", "runtime", "shared", "container process에 주입할 수 있는 설정값; secret 관리 자체와 동일하지 않다."), node("compose", "runtime", summary="여러 container 서비스를 하나의 선언으로 구성·실행하는 Docker Compose 도구."),
        node("port-mapping", "network-exposure", summary="host port와 container port를 연결하는 설정이며 firewall rule과 같지 않다."), node("nginx", "network-exposure", "boundary", "HTTP를 제공하거나 reverse proxy로 동작할 수 있는 웹 서버·프록시."), node("deployment", "deployment", "boundary", "build artifact를 실행 환경에 출시하는 과정으로 build와 구분된다."), node("health-check-endpoint", "deployment", "boundary", "운영 환경이 애플리케이션 상태를 확인하는 HTTP endpoint."), node("docker-hub", "deployment", summary="container image를 저장·배포하는 registry 서비스."),
        node("volume", "storage", summary="container 수명과 분리해 관리할 수 있는 Docker 저장소이며 bind mount와 완전히 동일하지 않다."), node("bind-mount", "storage", summary="host의 경로를 container에 직접 연결하는 mount 방식."), node("vm-vs-container", "storage", "foundation", "VM과 container는 격리 방식과 OS kernel 공유 방식이 다름을 비교하는 기준."), node("cli", "operations", "shared", "개발자와 운영자가 command로 도구를 제어하는 인터페이스."), node("docker-logs", "operations", summary="container의 표준 출력·오류 log를 확인하는 Docker command."),
    ]
    devops_routes = [
        {"id":"source-to-container","label":"코드가 컨테이너가 되는 길","description":"Dockerfile과 base image instructions가 image를 만들고, image에서 container가 실행된다.","nodeIds":["term:dockerfile","term:base-image","term:docker-image","term:docker-container"],"scope":"field"},
        {"id":"multi-service","label":"여러 서비스를 띄우는 길","description":"image 기반 container를 Compose가 network·storage 설정과 함께 구성한다.","nodeIds":["term:docker-image","term:docker-container","term:compose","term:volume"],"scope":"field"},
        {"id":"expose-service","label":"서비스가 외부에 보이는 길","description":"container port를 mapping하고 Nginx 같은 proxy를 거쳐 deployment 환경에 노출한다.","nodeIds":["term:docker-container","term:port-mapping","term:nginx","term:deployment","term:health-check-endpoint"],"scope":"field"},
    ]
    maps["devops-infrastructure"] = graph("devops-infrastructure", "devops-infrastructure", "DevOps / Infrastructure", "image, container, deployment와 운영 경계가 어떻게 이어지는지 살펴봅니다.", regions(("build-image","Build / Image","재현 가능한 image 생성."),("runtime","Runtime","container process와 구성."),("network-exposure","Network","서비스 노출 경계."),("storage","Storage","지속 데이터와 mount."),("deployment","Deployment","출시와 상태 확인."),("operations","Operations","명령과 log 관찰.")), devops_routes, devops_nodes, [
        edge("docker","uses","dockerfile","Docker tooling은 Dockerfile instructions로 image build를 실행할 수 있다.",DOC), edge("dockerfile","uses","base-image","Dockerfile은 base image에서 build를 시작할 수 있다.",DOC), edge("dockerfile","provided_by","docker-image","Dockerfile build 결과는 image다.",DOC), edge("layer","based_on","docker-image","image는 build layer들로 구성될 수 있다.",DOC), edge("docker-image","provided_by","docker-container","container는 image로부터 생성되어 실행된다.",DOC), edge("docker-container","uses","containerd-runc","container runtime 구성요소가 실행을 지원한다.",DOC), edge("compose","uses","docker-container","Compose는 여러 container service를 구성한다.",DOC), edge("environment-variable","provided_by","docker-container","container 실행 시 environment를 process에 전달할 수 있다.",DOC), edge("port-mapping","interacts_with","docker-container","port mapping은 host와 container network port를 연결한다.",DOC), edge("nginx","interacts_with","port-mapping","reverse proxy가 published port의 application에 요청을 전달할 수 있다.",DOC,"MEDIUM","architectural-inference"), edge("deployment","uses","docker-image","deployment는 image artifact를 실행 환경에 올릴 수 있다.",DOC), edge("health-check-endpoint","interacts_with","deployment","deployment 운영은 health endpoint로 상태를 확인할 수 있다.",DOC), edge("docker-hub","provided_by","docker-image","registry는 image를 저장하고 배포한다.",DOC), edge("volume","interacts_with","docker-container","volume은 container에 persistent storage를 제공한다.",DOC), edge("bind-mount","compare_with","volume","bind mount와 volume은 storage source와 관리 주체가 다르다.",DOC), edge("vm-vs-container","compare_with","docker-container","container와 VM은 OS kernel과 격리 모델이 다르다.",DOC), edge("cli","uses","docker","CLI로 Docker tooling을 제어한다.",DOC), edge("docker-logs","uses","docker-container","docker logs는 container가 낸 log를 조회한다.",DOC),
    ])
    overlays["devops-infrastructure"] = [overlay("devops-infrastructure","preliminary-m01","예비과정 M01 관련 기술","Docker 환경에서 image·container·Compose와 운영 확인 흐름을 강조합니다.",[("docker","container tooling을 사용한다.","direct"),("dockerfile","image build instructions를 작성한다.","direct"),("docker-image","실행 image를 만든다.","direct"),("docker-container","container를 실행한다.","direct"),("compose","여러 service를 구성한다.","direct"),("volume","지속 데이터 mount를 구성한다.","direct"),("bind-mount","host 경로를 연결한다.","direct"),("port-mapping","host와 container port를 연결한다.","direct"),("nginx","proxy service를 구성한다.","direct"),("environment-variable","runtime 설정을 전달한다.","direct"),("docker-logs","실행 log를 확인한다.","direct"),("cli","명령으로 환경을 제어한다.","direct")],["source-to-container","multi-service","expose-service"])]

    network_nodes = [
        node("virtual-private-cloud", "cloud-network", summary="cloud provider 안에서 격리해 구성하는 virtual network이며 일반 network 전체와 같지 않다."), node("subnet", "cloud-network", summary="IP address 범위를 나눈 network segment이며 VLAN과 동의어가 아니다."), node("public-subnet", "cloud-network", summary="route와 gateway 구성에 따라 internet-facing 경로를 둘 수 있는 subnet; public IP 보유 여부만으로 정의되지 않는다."), node("route-table", "routing", summary="destination prefix별 next hop을 고르는 규칙 모음이며 router 장비 자체가 아니다."), node("internet-gateway", "routing", summary="VPC와 internet 사이의 통신을 가능하게 하는 gateway."), node("nat-gateway", "routing", summary="private address의 outbound translation을 지원하는 gateway로 firewall과 다른 역할이다."), node("cidr", "addressing", "foundation", "IP prefix와 address block 크기를 표기하는 방식."), node("public-ip", "addressing", summary="internet routing이 가능한 전역 address; device의 영구 identity가 아니다."), node("socket-port", "addressing", summary="IP endpoint 안에서 application을 구분하는 transport port이며 물리 connector가 아니다."),
        node("tcp", "transport", "foundation", "순서·신뢰성 제어를 제공하는 transport protocol."), node("http", "web-protocol", summary="request와 response 의미를 정의하는 application protocol이며 TCP와 같지 않다."), node("https", "web-protocol", "shared", "HTTP에 TLS 보호를 적용한 secure transport 사용 방식; 별개의 application semantics가 아니다."), node("http-request", "web-protocol", "boundary", "client가 server에 보내는 HTTP message."), node("http-request-response", "web-protocol", "shared", "HTTP client-server 상호작용의 request/response 모델."), node("http-status-code", "web-protocol", summary="HTTP response 결과 범주를 표현하는 numeric status code."), node("curl", "web-protocol", "shared", "HTTP 등 network request를 command line에서 보내고 검사하는 client tool."),
        node("localhost", "name-resolution", summary="현재 host 자신을 가리키는 loopback name."), node("default-route-any-ipv4", "routing", summary="더 구체적 route가 없을 때 IPv4 traffic에 적용할 기본 경로."),
    ]
    network_routes = [
        {"id":"address-to-route","label":"주소를 찾아가는 길","description":"CIDR로 address range를 나누고 route table이 destination에 맞는 gateway 경로를 선택한다.","nodeIds":["term:cidr","term:subnet","term:route-table","term:internet-gateway"],"scope":"field"},
        {"id":"web-request","label":"웹 요청이 이동하는 길","description":"HTTP request/response는 TCP transport와 IP endpoint를 통해 server로 이동한다.","nodeIds":["term:http-request","term:http","term:tcp","term:socket-port","term:http-request-response"],"scope":"field"},
        {"id":"cloud-network-path","label":"클라우드 네트워크 경로","description":"VPC 안에서 subnet과 route table, gateway를 조합해 connectivity를 설계한다.","nodeIds":["term:virtual-private-cloud","term:subnet","term:route-table","term:internet-gateway"],"scope":"field"},
    ]
    maps["network-web-protocol"] = graph("network-web-protocol", "network-web-protocol", "Network / Web Protocol", "주소, routing, transport, HTTP와 cloud network 경계를 하나의 network 개념 지도로 살펴봅니다.", regions(("addressing","Addressing","IP 범위와 endpoint."),("routing","Routing","목적지에 맞는 다음 hop."),("transport","Transport","전송 계층의 보장."),("web-protocol","Web Protocol","HTTP message와 상태."),("cloud-network","Cloud Network","VPC의 논리 network."),("name-resolution","Local Context","local endpoint를 구분.")), network_routes, network_nodes, [
        edge("cidr","uses","subnet","subnet은 보통 CIDR prefix로 address range를 정의한다.",RFC), edge("public-subnet","is_a","subnet","public subnet은 subnet의 routing context다.",RFC), edge("virtual-private-cloud","uses","subnet","VPC는 하나 이상의 subnet으로 나뉠 수 있다.",RFC), edge("route-table","interacts_with","subnet","subnet traffic은 연결된 route table의 규칙을 따른다.",RFC), edge("route-table","uses","internet-gateway","internet-bound route는 internet gateway를 next hop으로 둘 수 있다.",RFC), edge("nat-gateway","interacts_with","route-table","private subnet의 outbound route가 NAT gateway를 향할 수 있다.",RFC), edge("default-route-any-ipv4","is_a","route-table","default route는 route table 안의 한 route rule이다.",RFC), edge("public-ip","interacts_with","internet-gateway","public IP traffic은 internet gateway를 통한 routing과 연관된다.",RFC), edge("socket-port","based_on","tcp","TCP port는 transport endpoint의 일부다.",RFC), edge("http","uses","tcp","HTTP/1.1은 TCP transport 위에서 전달될 수 있다.",RFC), edge("https","based_on","http","HTTPS는 HTTP semantics에 TLS protection을 더한다.",RFC), edge("http-request","is_a","http","HTTP request는 HTTP message의 한 방향이다.",RFC), edge("http-request-response","uses","http-request","request/response cycle은 HTTP request와 response로 구성된다.",RFC), edge("http-status-code","provided_by","http-request-response","status code는 HTTP response의 결과를 표현한다.",RFC), edge("curl","uses","http","curl은 HTTP request를 보내고 response를 검사할 수 있다.",RFC), edge("localhost","interacts_with","socket-port","localhost에서도 port로 local service endpoint를 구분한다.",RFC),
    ])
    overlays["network-web-protocol"] = [overlay("network-web-protocol","main-m05","본과정 M05 관련 기술","특정 cloud vendor 도면이 아니라 VPC, subnet, routing과 web connectivity의 공통 개념을 강조합니다.",[("virtual-private-cloud","VPC network를 구성한다.","direct"),("subnet","network segment를 나눈다.","direct"),("public-subnet","public-facing subnet을 구성한다.","direct"),("cidr","address range를 계산한다.","required"),("route-table","traffic route를 정의한다.","direct"),("internet-gateway","internet connectivity를 제공한다.","direct"),("nat-gateway","outbound path를 검토한다.","related"),("public-ip","external access address를 이해한다.","required"),("socket-port","service endpoint를 구분한다.","required"),("tcp","transport를 이해한다.","direct"),("https","secure web traffic을 제공한다.","direct"),("http-status-code","health response를 확인한다.","direct"),("curl","endpoint를 검사한다.","direct"),("localhost","local verification을 한다.","direct")],["address-to-route","cloud-network-path","web-request"])]

    backend_nodes = [
        node("uvicorn", "server-runtime", summary="ASGI application을 실행하는 server implementation이며 FastAPI application 자체가 아니다."), node("asgi", "server-runtime", "foundation", "async Python web server와 application 사이의 interface specification."), node("fastapi", "server-runtime", summary="Python API framework이며 web server 자체나 Nginx replacement가 아니다."), node("http-request-response", "request-handling", "boundary", "client와 backend가 request와 response를 주고받는 network boundary."), node("router-layer", "request-handling", summary="HTTP path와 method를 handler에 연결하는 application layer."), node("http-get", "request-handling", "boundary", "resource 조회에 흔히 쓰는 HTTP method."), node("http-post", "request-handling", "boundary", "resource 생성이나 처리 요청에 흔히 쓰는 HTTP method."), node("http-303-see-other", "request-handling", "boundary", "다른 URI로 GET하도록 안내하는 redirect response status."), node("redirectresponse", "request-handling", summary="FastAPI/Starlette에서 redirect response를 만드는 response class."),
        node("rest-api", "api-design", "shared", "HTTP resources와 uniform interface constraints를 활용하는 API architectural style; 모든 HTTP API와 동의어는 아니다."), node("crud", "api-design", summary="create, read, update, delete 데이터 작업의 분류이며 REST와 동의어가 아니다."), node("service-layer", "application-logic", summary="application use case를 모으는 선택 가능한 구조; framework의 필수 계층은 아니다."), node("repository-layer", "application-logic", summary="data access 세부사항을 application logic에서 분리할 수 있는 layer."), node("request-response-cycle", "application-logic", "foundation", "request가 routing, handling, response로 흐르는 application lifecycle."),
        node("sqlalchemy", "data-access", "boundary", "Python SQL toolkit와 ORM library."), node("database-session", "data-access", "boundary", "database interaction의 unit of work와 transaction state를 관리하는 session."), node("post-redirect-get", "integration", summary="POST 처리 뒤 redirect하고 GET으로 결과를 보여주는 web interaction pattern."), node("jinja2", "integration", summary="server-side template engine."), node("templateresponse", "integration", summary="template rendering result를 HTTP response로 보내는 response type."), node("html-form", "integration", "boundary", "browser가 HTTP request를 구성해 보내는 HTML control collection."),
    ]
    backend_routes = [
        {"id":"request-to-response","label":"요청이 처리되는 길","description":"HTTP request가 router와 handler/application logic을 거쳐 response가 된다.","nodeIds":["term:http-request-response","term:router-layer","term:fastapi","term:service-layer","term:request-response-cycle"],"scope":"field"},
        {"id":"save-post","label":"게시글이 저장되는 길","description":"POST request의 application logic이 repository와 database session을 통해 CRUD 작업을 수행한다.","nodeIds":["term:http-post","term:service-layer","term:repository-layer","term:database-session","term:crud"],"scope":"field"},
        {"id":"api-visible","label":"API가 보이는 길","description":"ASGI server가 FastAPI app을 실행하고 router endpoint가 REST API context를 드러낸다.","nodeIds":["term:uvicorn","term:asgi","term:fastapi","term:router-layer","term:rest-api"],"scope":"field"},
    ]
    maps["backend-server-api"] = graph("backend-server-api", "backend-server-api", "Backend / Server / API", "backend 핵심과 HTTP, application logic, data access가 만나는 경계를 살펴봅니다.", regions(("server-runtime","Server / Runtime","application과 server 실행."),("request-handling","Request Handling","route와 HTTP response."),("api-design","API","resource operation의 표현."),("application-logic","Application Logic","use case와 계층."),("data-access","Data Access","DB session과 persistence 경계."),("integration","Integration","form, template, redirect.")), backend_routes, backend_nodes, [
        edge("uvicorn","uses","asgi","Uvicorn은 ASGI application을 실행한다.",FASTAPI), edge("fastapi","based_on","asgi","FastAPI는 ASGI deployment와 함께 동작한다.",FASTAPI), edge("router-layer","uses","fastapi","FastAPI router가 path operation을 application에 등록한다.",FASTAPI), edge("http-get","interacts_with","router-layer","GET request는 route handler로 dispatch된다.",RFC), edge("http-post","interacts_with","router-layer","POST request는 route handler로 dispatch된다.",RFC), edge("http-request-response","interacts_with","router-layer","router는 request를 handler로 보내 response를 만든다.",FASTAPI), edge("rest-api","interacts_with","http-request-response","REST API는 HTTP request/response interface로 노출될 수 있다.",RFC,"MEDIUM","architectural-inference"), edge("crud","interacts_with","rest-api","CRUD operation은 REST resource design과 함께 표현될 수 있지만 둘은 동일하지 않다.",FASTAPI,"MEDIUM","architectural-inference"), edge("service-layer","interacts_with","repository-layer","service layer는 repository를 통해 persistence를 분리할 수 있다.",FASTAPI,"MEDIUM","architectural-inference"), edge("request-response-cycle","uses","service-layer","handler는 request cycle 안에서 application service를 호출할 수 있다.",FASTAPI,"MEDIUM","architectural-inference"), edge("repository-layer","uses","database-session","repository는 database session으로 query를 수행할 수 있다.",FASTAPI,"MEDIUM","architectural-inference"), edge("sqlalchemy","provided_by","database-session","SQLAlchemy session이 database interaction state를 관리한다.","https://docs.sqlalchemy.org/"), edge("html-form","uses","http-post","HTML form은 POST request를 만들 수 있다.",RFC), edge("post-redirect-get","uses","http-303-see-other","PRG flow는 POST 뒤 303 redirect를 사용할 수 있다.",RFC), edge("redirectresponse","provided_by","http-303-see-other","RedirectResponse는 redirect status와 Location response를 만든다.",FASTAPI), edge("templateresponse","uses","jinja2","TemplateResponse는 Jinja2 template rendering과 함께 사용된다.",FASTAPI),
    ])
    overlays["backend-server-api"] = [overlay("backend-server-api","main-m12","본과정 M12 관련 기술","FastAPI CRUD service의 request handling, layer, data access를 강조합니다.",[("fastapi","게시판 application framework다.","direct"),("uvicorn","ASGI application을 실행한다.","direct"),("asgi","server/application interface를 이해한다.","required"),("router-layer","path operation을 구성한다.","direct"),("http-get","조회 endpoint method다.","direct"),("http-post","form submission method다.","direct"),("crud","게시글 create/read/update/delete를 구현한다.","direct"),("service-layer","business logic을 분리한다.","direct"),("repository-layer","data access를 분리한다.","direct"),("sqlalchemy","ORM/data toolkit을 사용한다.","direct"),("database-session","DB interaction session을 관리한다.","required"),("post-redirect-get","POST 뒤 결과 화면 흐름을 만든다.","direct"),("http-303-see-other","redirect status를 이해한다.","direct"),("redirectresponse","redirect response를 만든다.","direct"),("jinja2","template rendering을 한다.","direct"),("templateresponse","rendered response를 보낸다.","direct"),("html-form","browser form request를 받는다.","direct")],["request-to-response","save-post","api-visible"])]

    security_nodes = [
        node("login", "identity", summary="사용자가 credential을 제출해 authentication flow를 시작하는 interaction."), node("password-credential", "identity", summary="사용자가 자신임을 증명하기 위해 제시하는 password credential."), node("password-hashing", "identity", summary="password verification을 위해 one-way hash를 저장·비교하는 방식이며 encryption과 다르다."), node("authentication", "authentication", summary="claim한 identity가 맞는지 확인하는 과정; authorization과 다르다."), node("authentication-token", "authentication", "boundary", "authenticated request에 identity claim을 전달하는 credential artifact."), node("json-web-token", "token-session", summary="claims를 담은 signed token format이며 authentication 자체나 encryption의 동의어가 아니다."), node("refresh-token", "token-session", summary="새 access credential을 얻는 데 쓰는 장기 credential로 access token과 목적·수명이 다르다."), node("login-session", "token-session", summary="server가 인증 상태를 보관하고 client identifier로 연결하는 session-based authentication."), node("cookie", "token-session", "shared", "browser가 HTTP state를 저장·전송하는 mechanism으로 session 그 자체와 같지 않다."),
        node("authorization", "authorization", summary="authenticated principal이 요청한 action/resource에 허용되는지 결정하는 과정."), node("access-control", "authorization", "foundation", "주체가 resource에 수행할 수 있는 action을 제한하는 정책 체계."), node("rbac", "authorization", summary="role에 permission을 연결해 authorization을 결정하는 model."), node("protected-route", "authorization", "boundary", "보호 resource로 향하는 route; client UI hide만으로 server authorization이 보장되지는 않는다."), node("public-route", "authorization", summary="authentication 없이 접근 가능한 route."),
        node("oauth-2-0", "oauth", summary="client가 resource owner 대신 protected resource access를 위임받는 authorization framework; login protocol 자체가 아니다."), node("oauth2-authorization-code", "oauth", "boundary", "authorization code를 token으로 교환하는 OAuth 2.0 grant flow."), node("https", "transport-browser", "shared", "HTTP traffic의 confidentiality·integrity를 TLS로 보호하지만 application authorization을 제공하지는 않는다."), node("csrf", "transport-browser", summary="browser가 가진 credential을 악용한 cross-site request 위조 공격과 방어 고려사항."), node("api-key", "transport-browser", "shared", "application 또는 service를 식별·인가하는 secret credential로 user login token과 구분된다."), node("environment-variable", "transport-browser", "shared", "runtime configuration 전달 수단; secret을 source에 hardcode하지 않도록 돕는 경계."),
    ]
    security_routes = [
        {"id":"login-state","label":"로그인 상태가 생기는 길","description":"credential을 authentication으로 검증한 뒤 session 또는 token으로 authenticated request를 연결한다.","nodeIds":["term:password-credential","term:authentication","term:login-session","term:cookie","term:authentication-token"],"scope":"field"},
        {"id":"token-authorize","label":"토큰 인증의 길","description":"login 뒤 authentication token/JWT를 검증하고 authorization으로 protected resource access를 결정한다.","nodeIds":["term:login","term:authentication-token","term:json-web-token","term:authorization","term:protected-route"],"scope":"field"},
        {"id":"oauth-delegation","label":"OAuth 위임의 길","description":"client는 authorization code grant를 통해 access delegation을 받고 protected resource에 접근한다.","nodeIds":["term:oauth-2-0","term:oauth2-authorization-code","term:authentication-token","term:protected-route"],"scope":"field"},
    ]
    maps["security-identity"] = graph("security-identity", "security-identity", "Security / Identity", "identity, authentication, token/session, authorization과 browser·transport 경계를 구분해 살펴봅니다.", regions(("identity","Identity","credential과 password handling."),("authentication","Authentication","identity verification."),("token-session","Token / Session","authenticated state 전달."),("authorization","Authorization","permission과 protected resource."),("oauth","OAuth","delegated authorization."),("transport-browser","Transport / Browser","HTTPS, browser 공격면, secret handling.")), security_routes, security_nodes, [
        edge("login","uses","password-credential","login flow는 password credential을 제출받을 수 있다.",OWASP), edge("password-hashing","interacts_with","password-credential","server는 password를 plaintext가 아닌 hash verification으로 처리해야 한다.",OWASP), edge("authentication","uses","password-credential","authentication은 credential을 검증해 identity claim을 확인한다.",OWASP), edge("authentication-token","provided_by","authentication","성공한 authentication 뒤 token credential을 발급할 수 있다.",OWASP), edge("json-web-token","is_a","authentication-token","JWT는 token format의 한 선택지이며 token 자체와 authentication을 동일시하지 않는다.",RFC), edge("refresh-token","compare_with","authentication-token","refresh token은 access credential 갱신용이며 access token과 수명·용도가 다르다.",OWASP), edge("login-session","interacts_with","cookie","session identifier는 browser cookie로 전달될 수 있으나 cookie와 session은 같은 개념이 아니다.",OWASP), edge("authorization","based_on","authentication","authorization은 보통 authenticated principal의 identity/claims를 입력으로 사용한다.",OWASP), edge("access-control","provided_by","authorization","authorization decision은 access control policy를 적용한다.",OWASP), edge("rbac","is_a","access-control","RBAC은 role 기반 access control model이다.",OWASP), edge("protected-route","uses","authorization","protected route의 server handler는 authorization을 검사해야 한다.",OWASP), edge("public-route","compare_with","protected-route","public route는 protected route와 달리 authentication 없이 접근할 수 있다.",OWASP), edge("oauth-2-0","uses","authorization","OAuth 2.0은 delegated authorization framework다.",RFC), edge("oauth2-authorization-code","is_a","oauth-2-0","authorization code grant는 OAuth 2.0 flow의 하나다.",RFC), edge("oauth2-authorization-code","provided_by","authentication-token","token endpoint가 code 교환 뒤 access token을 발급할 수 있다.",RFC), edge("https","interacts_with","cookie","secure cookie transport는 HTTPS protection에 의존한다.",OWASP), edge("csrf","interacts_with","cookie","browser cookie credential은 CSRF threat model과 관련된다.",OWASP), edge("api-key","compare_with","authentication-token","API key는 일반적으로 end-user authentication token과 다른 credential이다.",OWASP), edge("environment-variable","interacts_with","api-key","deployment environment variable로 API secret을 주입할 수 있다.",OWASP),
    ])
    overlays["security-identity"] = [overlay("security-identity","main-m13","본과정 M13 관련 기술","로그인, JWT, OAuth, access/refresh token과 authorization·protected resource 경계를 강조합니다.",[("login","로그인 flow를 구현한다.","direct"),("password-credential","사용자 credential을 검증한다.","required"),("password-hashing","password를 안전하게 저장·검증한다.","direct"),("authentication","사용자 identity를 확인한다.","direct"),("authentication-token","authenticated request credential을 다룬다.","required"),("json-web-token","JWT 기반 token을 다룬다.","direct"),("refresh-token","token refresh 개념을 확장한다.","related"),("login-session","session authentication을 구현한다.","direct"),("cookie","browser session state를 연결한다.","required"),("authorization","resource access를 결정한다.","direct"),("rbac","role authorization을 확장한다.","related"),("protected-route","보호 resource route를 구현한다.","direct"),("public-route","공개 route와 비교한다.","direct"),("oauth-2-0","OAuth delegated authorization을 구현한다.","direct"),("oauth2-authorization-code","authorization code flow를 확장한다.","related"),("https","secure transport context를 유지한다.","related")],["login-state","token-authorize","oauth-delegation"])]

    for map_id, payload in maps.items():
        directory = ROOT / "data/knowledge-maps" / map_id
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "knowledge-map.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        overlay_dir = directory / "overlays"; overlay_dir.mkdir(exist_ok=True)
        for item in overlays[map_id]:
            (overlay_dir / f"{item['missionId']}.json").write_text(json.dumps(item, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

if __name__ == "__main__":
    build()
