#!/usr/bin/env python3
"""Write Sprint 8 content for exactly the S7-B01 terms and their planned tiers."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import sys as _sys; _sys.path.insert(0, str(Path(__file__).resolve().parent))
from content_generation_guard import assert_generation_allowed  # R12 재발 방지
assert_generation_allowed(__file__)

PLAN = ROOT / "data/reviews/content-tier-sprint7.json"
MASTER = ROOT / "data/curated/glossary-master-v0.1.yaml"
TERMS = ROOT / "content/terms"
BATCH_ID = "S7-B01"

# title, summary, easy explanation, technical definition, mission context,
# example, boundary, related ids, misconception, peer question, how it works.
CONTENT = {
"deadlock": ("Deadlock", "서로가 가진 자원을 기다리느라 어떤 작업도 더 진행하지 못하는 상태입니다.", "두 사람이 서로의 열쇠를 기다리며 문을 열지 못하는 상황과 비슷합니다.", "Deadlock은 둘 이상의 실행 흐름이 lock을 획득한 뒤 다른 lock의 해제를 무한히 기다리는 동시성 장애입니다. 대기 순환이 생기면 CPU가 충분해도 작업은 끝나지 않습니다.", "M08에서 lock 대기 장애의 원인을 구분하고, 멈춘 프로세스의 조치를 설명하는 기준입니다.", "```python\n# T1: A를 잡고 B 대기 / T2: B를 잡고 A 대기\n# lock 획득 순서를 A → B로 통일하면 순환을 막을 수 있다.\n```", "timeout은 관찰과 복구에 도움을 주지만 설계상 순환 대기를 자동으로 없애지는 않습니다.", ["lock", "mutex", "race-condition", "process"], "Deadlock은 단순히 프로그램이 느린 상태가 아닙니다. 진행 조건 자체가 막힌 상태입니다.", "두 lock을 서로 다른 순서로 잡는 코드가 왜 deadlock을 만들 수 있나요?", "1. 실행 흐름이 첫 lock을 각각 획득합니다.\n2. 각 흐름이 상대가 가진 두 번째 lock을 기다립니다.\n3. 아무도 첫 lock을 놓지 못해 대기 순환이 유지됩니다."),
"input-validation": ("입력 검증", "외부에서 받은 값이 형식·범위·규칙에 맞는지 사용 전에 확인하는 과정입니다.", "문 앞에서 초대장과 인원수를 확인하는 것처럼, 프로그램에 넣기 전에 값이 쓸 수 있는 것인지 확인합니다.", "Input validation은 HTTP 요청, CLI 인자, 파일, 폼 값처럼 신뢰할 수 없는 입력을 허용 목록·타입·길이·범위·도메인 규칙으로 검사하고 실패를 명확히 처리하는 작업입니다.", "M03 API와 M12 서버 입력에서 잘못된 값이 비즈니스 로직이나 DB까지 들어가지 않게 합니다.", "```python\nage = int(raw_age)\nif not 0 <= age <= 150:\n    raise ValueError('age 범위 오류')\n```", "클라이언트 검증은 UX를 위한 보조 수단입니다. 서버도 독립적으로 같은 핵심 규칙을 검증해야 합니다.", ["output-validation", "form-validation", "sql-injection", "authentication"], "타입 변환에 성공했다고 입력이 업무 규칙까지 만족하는 것은 아닙니다.", "브라우저 폼 검증만으로 서버 입력 검증을 대체할 수 없는 이유는 무엇인가요?", "1. 입력의 출처와 기대 스키마를 정합니다.\n2. 형식·범위·관계 규칙을 확인합니다.\n3. 실패는 안전한 오류로, 성공 값만 다음 계층으로 전달합니다."),
"lock": ("Lock", "공유 자원을 한 번에 한 실행 흐름만 변경하도록 만드는 동기화 장치입니다.", "한 사람이 쓰는 화장실 열쇠처럼, 열쇠를 가진 작업만 안의 자원을 바꿀 수 있게 합니다.", "Lock은 임계 구역에 들어가기 전 획득하고 작업 뒤 해제하는 배타 제어입니다. 올바른 범위·해제·획득 순서가 없으면 race condition이나 deadlock을 만들 수 있습니다.", "M08에서 동시에 실행되는 작업이 공유 상태를 안전하게 다루는 방법을 설명합니다.", "```python\nwith lock:\n    balance += 1  # 읽기·수정·쓰기를 한 임계 구역으로 묶는다\n```", "모든 코드를 lock으로 감싸면 안전해 보일 수 있지만 병렬성을 낮추고 오래 잡은 lock은 병목이 됩니다.", ["mutex", "race-condition", "deadlock", "thread"], "Lock은 데이터를 자동으로 올바르게 만드는 기능이 아니라 접근 순서를 제어하는 기능입니다.", "balance += 1을 lock 없이 두 실행 흐름이 수행하면 어떤 결과가 생길 수 있나요?", "1. lock을 획득한 흐름만 임계 구역에 들어갑니다.\n2. 공유 값을 읽고 변경합니다.\n3. 예외가 나도 해제되도록 finally 또는 context manager로 lock을 놓습니다."),
"nginx": ("Nginx", "HTTP 요청을 받아 정적 파일을 제공하거나 애플리케이션 서버로 전달할 수 있는 웹 서버와 리버스 프록시입니다.", "건물 현관에서 방문자를 맞아 알맞은 부서로 안내하는 안내 데스크와 비슷합니다.", "Nginx는 클라이언트 연결을 처리하고 정적 콘텐츠를 직접 응답하거나, 경로·호스트 규칙에 따라 upstream 애플리케이션으로 요청을 프록시할 수 있습니다. 애플리케이션 프레임워크와는 별도 프로세스입니다.", "M05 배포에서 공개 HTTP 진입점과 실행 중인 웹 애플리케이션의 역할을 분리해 확인합니다.", "```nginx\nlocation /api/ {\n  proxy_pass http://127.0.0.1:8000;\n}\n```", "Nginx 설정이 정상이어도 upstream 프로세스, DNS, TLS 인증서가 실패하면 서비스 전체가 정상이라는 뜻은 아닙니다.", ["http", "health-check", "deployment"], "Nginx가 Python/Node 애플리케이션 코드를 직접 실행하는 프레임워크라는 생각은 맞지 않습니다.", "Nginx가 502를 반환할 때 웹 서버와 upstream 중 어디를 어떻게 나누어 확인하겠습니까?", "1. 클라이언트 요청을 수신합니다.\n2. 정적 응답 또는 location 규칙을 고릅니다.\n3. 필요하면 upstream에 전달하고 응답을 다시 클라이언트에 보냅니다."),
"state-change": ("상태 변경", "프로그램이 기억하는 값이 이전 값에서 새 값으로 바뀌는 사건입니다.", "장바구니 수량이 1에서 2가 되는 것처럼, 화면이나 프로그램이 기억하던 사실이 달라지는 일입니다.", "State change는 UI·도메인·서버 상태의 값이 이벤트나 처리 결과로 바뀌는 것을 말합니다. 변경 자체와 화면 렌더링, 영속 저장, 네트워크 전송은 서로 다른 단계일 수 있습니다.", "M01의 사용자 클릭 처리에서 이벤트가 상태를 바꾸고 화면에 반영되는 흐름을 설명합니다.", "```js\nsetCount(previous => previous + 1);\n```", "객체를 제자리에서 바꾸면 프레임워크가 변경을 감지하지 못할 수 있으므로 해당 상태 관리 방식의 불변성 규칙을 확인해야 합니다.", ["state-transition", "ui-state", "react-state", "user-event"], "상태가 바뀌었다고 즉시 DOM이 같은 방식으로 갱신된다고 단정할 수는 없습니다.", "클릭 이벤트, 상태 변경, 화면 갱신을 왜 서로 다른 단계로 설명해야 하나요?", "1. 이벤트가 의도를 전달합니다.\n2. 상태 업데이트가 이전 값을 기준으로 새 값을 계산합니다.\n3. UI 계층이 새 상태를 사용해 다음 화면을 결정합니다."),
"state-transition": ("State Transition", "상태가 허용된 규칙에 따라 한 상태에서 다른 상태로 이동하는 것입니다.", "배송이 ‘결제 대기 → 결제 완료 → 발송됨’ 순서로만 바뀌는 표지판과 비슷합니다.", "State transition은 상태 집합과 전이 규칙으로 현재 상태에서 가능한 다음 상태를 제한합니다. 단순 값 변경보다, 어떤 이벤트가 어떤 변경을 허용하는지까지 포함합니다.", "M13의 인증·보호 기능처럼 요청 처리 단계와 비즈니스 상태의 유효한 순서를 설계할 때 필요합니다.", "```text\nPENDING --approve--> APPROVED\nPENDING --reject--> REJECTED\n```", "이미 종료된 상태를 다시 승인하는 전이를 허용할지는 도메인 규칙이며, 상태 이름만으로 자동 결정되지 않습니다.", ["state-change", "ui-state", "verification", "business-logic"], "모든 state change가 의미 있는 state transition은 아닙니다. 전이에는 허용 규칙이 필요합니다.", "PENDING 상태에서 approve와 reject가 동시에 들어오면 어떤 전이 규칙과 검증이 필요할까요?", "1. 현재 상태와 가능한 이벤트를 정의합니다.\n2. 이벤트가 허용되는지 검사합니다.\n3. 새 상태를 기록하고 필요한 후속 작업을 수행합니다."),
"cache": ("Cache", "다시 계산하거나 가져오는 비용이 큰 값을 가까운 곳에 임시로 저장해 더 빨리 재사용하는 저장소입니다.", "자주 찾는 책을 창고 대신 책상 위에 두는 것과 비슷합니다.", "Cache는 원본 데이터(source of truth)의 복사본을 메모리·브라우저·중간 서버 등에 두고 hit 때 빠르게 반환합니다. TTL, 무효화, eviction 정책이 없으면 오래된 값이나 메모리 압박 문제가 생깁니다.", "M09 Redis 활용에서 빠른 조회와 원본 데이터 일관성 사이의 trade-off를 설명합니다.", "```python\nvalue = cache.get(key)\nif value is None:\n    value = load_from_database(key)\n    cache.set(key, value, ttl=60)\n```", "Cache hit은 값이 최신이라는 보장이 아닙니다. 변경 직후에는 invalidation 또는 짧은 TTL 전략이 필요합니다.", ["time-to-live", "least-recently-used", "memoization", "redis"], "Cache는 데이터베이스를 무조건 대체하는 영구 저장소가 아닙니다.", "사용자 프로필을 수정한 뒤 cache를 갱신하거나 지워야 하는 이유는 무엇인가요?", "1. key로 캐시를 찾습니다.\n2. hit이면 복사본을 반환합니다.\n3. miss이면 원본에서 읽고 정책에 맞게 저장합니다.\n4. 만료·변경·용량 압박 때 항목을 갱신하거나 제거합니다."),
"console": ("콘솔", "명령을 입력하고 프로그램의 표준 출력·오류를 확인하는 텍스트 기반 인터페이스입니다.", "프로그램과 짧은 문장으로 대화하는 창입니다.", "Console은 터미널 창, 브라우저 개발자 도구, REPL처럼 텍스트 입출력을 보여 주는 환경을 가리킬 수 있습니다. shell 자체나 실행 중인 프로그램과는 구분해야 합니다.", "예비 M02에서 메뉴형 프로그램의 입력·출력과 오류 메시지를 확인하는 관찰 창입니다.", "```python\nprint('saved')\n```", "브라우저 console의 JavaScript 실행 환경과 운영체제 terminal의 shell 명령 환경은 같은 명령을 항상 지원하지 않습니다.", ["terminal", "shell", "read-eval-print-loop"], "console.log가 남는다고 애플리케이션의 정식 logging 체계가 완성된 것은 아닙니다.", "브라우저 콘솔과 터미널에서 실행할 수 있는 명령이 다른 이유는 무엇인가요?", None),
"decorator": ("Decorator", "함수나 클래스의 핵심 코드를 바꾸지 않고 앞뒤 동작을 덧붙이는 Python 문법과 패턴입니다.", "선물 상자 자체는 건드리지 않고 포장지와 리본을 더하는 것과 비슷합니다.", "Python decorator는 callable을 받아 새 callable을 반환하거나 객체를 변환합니다. `@name` 표기는 정의 직후 그 변환을 적용하는 문법 설탕입니다.", "M03에서 검증·로그처럼 여러 처리에 반복되는 관심사를 비즈니스 로직에서 분리할 때 사용합니다.", "```python\ndef logged(fn):\n    def wrapped(*args, **kwargs):\n        print(fn.__name__)\n        return fn(*args, **kwargs)\n    return wrapped\n```", "decorator가 함수의 서명·메타데이터를 가릴 수 있으므로 `functools.wraps`와 적용 순서를 확인해야 합니다.", ["separation-of-concerns", "logging", "function"], "Decorator는 상속이나 단순 주석이 아니라 실행 가능한 객체 변환입니다.", "검증 decorator를 여러 개 붙일 때 순서가 결과에 영향을 주는 이유는 무엇인가요?", None),
"generator": ("Generator", "필요한 값을 한꺼번에 만들지 않고 요청될 때마다 하나씩 내보내는 반복 가능한 실행 흐름입니다.", "물을 통째로 붓지 않고 수도꼭지를 열 때마다 한 컵씩 받는 방식과 비슷합니다.", "Python generator는 `yield`를 만나면 현재 지역 상태를 보존한 채 값을 내보내고, 다음 iteration에서 그 지점부터 재개합니다. 큰 입력을 지연 처리할 때 메모리를 줄일 수 있습니다.", "M03에서 파일 전체를 메모리에 올리지 않고 데이터를 스트리밍 처리하는 선택지입니다.", "```python\ndef lines(path):\n    with open(path) as file:\n        for line in file:\n            yield line.rstrip()\n```", "Generator는 한 번 소비하면 처음부터 다시 읽을 수 없는 iterator일 수 있으므로 재사용 요구를 확인해야 합니다.", ["yield", "iterator", "streaming"], "Generator가 항상 더 빠른 것은 아닙니다. 계산을 미루는 대신 반복 시점에 비용을 지불합니다.", "대용량 파일에서 list보다 generator가 메모리 사용량을 줄이는 이유는 무엇인가요?", None),
"health-check": ("Health Check", "서비스가 요청을 처리할 준비가 되었는지 관찰하기 위한 점검 신호나 엔드포인트입니다.", "가게 문이 열려 있는지와 실제 주문을 받을 수 있는지를 확인하는 점검입니다.", "Health check는 프로세스 생존(liveness)과 의존성까지 준비된 상태(readiness)를 구분할 수 있습니다. 상태 코드 하나만으로 모든 기능의 정상성을 증명하지는 않습니다.", "M07에서 프로세스·포트·서비스 상태를 재시작 전후로 확인합니다.", "```text\nGET /healthz -> 200 {status: ok}\n```", "DB 연결을 실제로 검사하는 readiness endpoint는 장애 전파 위험이 있으므로 timeout과 목적을 분명히 해야 합니다.", ["watchdog", "logging", "nginx"], "포트가 열려 있다는 사실과 애플리케이션이 요청을 성공 처리한다는 사실은 다릅니다.", "liveness와 readiness를 나누면 배포·재시작 판단이 어떻게 좋아지나요?", None),
"if-elif-else": ("조건문", "조건의 참·거짓에 따라 서로 다른 코드를 하나 선택해 실행하는 제어 구조입니다.", "갈림길 표지판을 보고 현재 조건에 맞는 길 하나를 고르는 것과 같습니다.", "Python의 `if`/`elif`/`else`는 위에서 아래로 조건을 평가하고 처음 참인 분기만 실행합니다. 조건 순서가 겹치면 먼저 쓴 조건이 우선합니다.", "예비 M02 메뉴 입력과 상태별 처리를 명확한 분기로 구현하는 기초입니다.", "```python\nif score >= 90:\n    grade = 'A'\nelif score >= 80:\n    grade = 'B'\nelse:\n    grade = 'C'\n```", "독립된 `if`를 여러 개 쓰면 여러 분기가 실행될 수 있어, 하나만 선택할 규칙에는 `elif`가 맞는지 확인해야 합니다.", ["loop", "input-validation", "state-transition"], "else는 오류 처리 전용이 아니라 앞선 모든 조건이 거짓일 때의 경로입니다.", "90점 조건을 80점 조건 뒤에 두면 왜 A 등급이 나오지 않나요?", None),
"layered-architecture": ("Layered Architecture", "역할이 다른 코드를 계층으로 나누고 의존 방향을 제한하는 설계 방식입니다.", "접수 창구, 업무 부서, 보관소가 각자 맡은 일을 하는 구조와 비슷합니다.", "Layered architecture는 보통 요청 진입부, 비즈니스 규칙, 데이터 접근을 분리합니다. 계층은 파일 개수 규칙이 아니라 변경 이유와 의존성을 관리하는 경계입니다.", "M12에서 Router·Service·Repository의 책임을 나누어 API 변경과 저장소 변경의 영향을 줄입니다.", "```text\nRouter → Service → Repository → Database\n```", "작은 프로그램에 계층을 과도하게 늘리면 탐색 비용만 커질 수 있으므로 실제 변경 축에 맞춰야 합니다.", ["separation-of-concerns", "dependency-injection", "repository-pattern"], "계층을 만들었다고 상위 계층이 하위 구현 세부사항에 의존하지 않게 되는 것은 아닙니다.", "Repository의 SQL 세부사항이 Router까지 새면 어떤 유지보수 문제가 생기나요?", None),
"log-rotation": ("Log Rotation", "로그 파일이 끝없이 커지지 않도록 크기·시간 기준으로 교체하고 오래된 파일을 보관·삭제하는 운영 정책입니다.", "영수증 철이 너무 두꺼워지기 전에 새 철로 넘기고 오래된 철을 정리하는 일입니다.", "Log rotation은 현재 로그를 새 파일로 전환하고, 보관 수·압축·삭제 규칙을 적용합니다. 애플리케이션이 파일을 계속 열어 둔 경우 reopen 방식도 고려해야 합니다.", "M07의 monitor.log 10MB/10개 보관 요구를 안정적인 디스크 사용량 관리로 연결합니다.", "```text\nmonitor.log → monitor.log.1 → monitor.log.2.gz\n```", "보관 개수만 정하고 로그 생성량을 모르면 디스크 고갈이나 필요한 조사 기록의 조기 삭제가 생길 수 있습니다.", ["logging", "disk-usage", "system-monitoring"], "Rotation은 로그 내용을 분석하는 기능이 아니라 파일 수명주기를 관리하는 기능입니다.", "10개 보관 정책에서 장애 조사에 필요한 로그가 사라지지 않게 무엇을 함께 정해야 하나요?", None),
"logging": ("Logging", "프로그램이 실행 중에 일어난 사건과 상태를 나중에 관찰할 수 있도록 구조화해 남기는 작업입니다.", "운영 중 무슨 일이 있었는지 남기는 항해 일지입니다.", "Logging은 시간, 수준, 메시지, 요청 식별자 같은 맥락을 기록해 디버깅·감사·운영 관찰을 돕습니다. 비밀값이나 개인정보는 기록하지 않도록 설계해야 합니다.", "M07에서 CPU·메모리 상태와 종료 사유를 monitor.log에 남겨 재현 가능한 점검 근거를 만듭니다.", "```python\nlogger.warning('cpu threshold exceeded', extra={'cpu': cpu})\n```", "로그를 많이 남기는 것만으로 관찰성이 좋아지지 않습니다. 수준, 형식, 보존 기간과 민감정보 정책이 필요합니다.", ["log-rotation", "root-cause-analysis", "health-check"], "print를 여러 곳에 넣는 것은 검색·보존·수준 제어가 가능한 운영 logging과 다릅니다.", "인증 토큰을 로그에 남기면 왜 장애 분석보다 큰 보안 문제가 될 수 있나요?", None),
"loop": ("반복문", "조건이 유지되거나 컬렉션에 항목이 있는 동안 같은 처리 구조를 반복 실행하는 제어 구조입니다.", "목록의 물건을 하나씩 확인할 때까지 같은 동작을 되풀이하는 것과 같습니다.", "Loop는 `for`처럼 순회 가능한 값의 각 항목을 처리하거나 `while`처럼 조건이 참인 동안 실행합니다. 종료 조건과 상태 갱신이 정확해야 무한 반복을 피할 수 있습니다.", "예비 M02 메뉴를 사용자가 종료할 때까지 다시 보여 주는 흐름을 구현합니다.", "```python\nwhile True:\n    command = input('> ')\n    if command == 'quit':\n        break\n```", "반복 안에서 컬렉션을 동시에 변경하면 항목 누락이나 예외가 날 수 있어 순회 방식에 맞는 처리가 필요합니다.", ["if-elif-else", "generator", "iterator"], "Loop는 재귀와 같지 않으며, 각각 상태·호출 스택·종료 방식을 다르게 관리합니다.", "while loop가 끝나려면 어떤 값 또는 조건이 반드시 변해야 하나요?", None),
"method": ("메서드", "클래스나 객체에 속해 그 객체의 데이터와 함께 동작하는 함수입니다.", "객체가 자기 상태를 다루기 위해 가진 행동 목록과 같습니다.", "Method는 인스턴스에 바인딩되어 첫 인자로 인스턴스(`self`)를 받거나, classmethod·staticmethod처럼 다른 바인딩 규칙을 가질 수 있습니다. 일반 함수와 호출 문맥이 다릅니다.", "예비 M02에서 클래스가 보유한 데이터를 읽고 바꾸는 동작을 책임 있게 묶습니다.", "```python\nclass Counter:\n    def increment(self):\n        self.value += 1\n```", "Method가 객체 상태를 바꾼다면 호출 순서와 불변 조건을 고려해야 하며, 모든 helper를 억지로 method로 만들 필요는 없습니다.", ["class", "attribute", "function"], "Method는 단순히 클래스 파일 안에 적힌 함수가 아니라 객체 또는 클래스와 바인딩된 호출 규칙을 가집니다.", "Counter.increment가 self를 받아야 하는 이유는 무엇인가요?", None),
"numpy-pandas": ("NumPy와 pandas", "수치 배열 처리와 표 형태 데이터 분석에 널리 쓰이는 Python 외부 라이브러리입니다.", "큰 숫자 표와 계산을 손으로 처리하지 않게 돕는 전문 도구 상자입니다.", "NumPy는 다차원 배열과 벡터화 연산을, pandas는 Series·DataFrame 기반의 표 데이터 조작을 제공합니다. 둘 다 Python 표준 라이브러리에는 포함되지 않습니다.", "예비 M03에서 외부 라이브러리 사용 금지 조건을 이해하고 허용된 도구 범위를 지키는 데 필요합니다.", "```python\n# import pandas as pd  # 프로젝트 정책이 금지하면 사용하지 않는다\n```", "라이브러리가 편리해도 의존성 정책·배포 환경·과제 요구사항이 허용하는지 먼저 확인해야 합니다.", ["standard-library", "python-virtual-environment", "requirements-txt"], "NumPy와 pandas는 같은 라이브러리가 아니며, 설치되어 있다고 표준 기능이 되는 것도 아닙니다.", "과제에서 표준 라이브러리만 허용할 때 pandas를 쓰면 어떤 문제가 생기나요?", None),
"python-cli": ("Python CLI", "Python 프로그램을 명령줄 인자와 표준 입출력으로 실행·자동화하는 인터페이스입니다.", "버튼 화면 대신 터미널에서 옵션을 붙여 프로그램에 일을 시키는 방식입니다.", "Python CLI는 `sys.argv` 또는 `argparse` 등으로 명령·옵션을 해석하고 exit code와 stdout/stderr로 결과를 전달합니다. 사람이 쓰는 명령과 다른 프로그램이 호출하는 계약이 됩니다.", "M06에서 Git 상태를 읽고 AI 호출을 수행하는 도구를 재현 가능하게 실행합니다.", "```python\nimport argparse\np = argparse.ArgumentParser()\np.add_argument('--repo', required=True)\nargs = p.parse_args()\n```", "출력에 사람용 설명과 기계 파싱용 데이터를 섞으면 자동화가 깨질 수 있으므로 채널과 형식을 정해야 합니다.", ["cli", "stdin-stdout", "exit-code"], "CLI는 Python interactive shell과 같지 않습니다. CLI는 인자·종료 코드가 있는 실행 인터페이스입니다.", "CLI가 실패했음을 shell script가 알 수 있게 하려면 무엇을 반환해야 하나요?", None),
"python-dataclass": ("Python dataclass", "데이터를 담는 클래스의 생성자·표현·비교 메서드를 선언으로 자동 생성해 주는 Python 기능입니다.", "같은 형식의 기록표를 매번 손으로 만들지 않고 필요한 칸만 선언하는 방식입니다.", "`@dataclass`는 type-annotated field를 바탕으로 `__init__`, `__repr__`, `__eq__` 등을 생성합니다. 기본값으로 가변 객체를 직접 쓰면 인스턴스 간 공유 문제가 생길 수 있습니다.", "M03의 Transaction 구조를 명확한 데이터 형태로 표현하는 후보입니다.", "```python\nfrom dataclasses import dataclass\n@dataclass\nclass Transaction:\n    amount: int\n    category: str\n```", "dataclass는 validation·영속성·불변성을 자동으로 모두 해결하지 않습니다. 필요한 규칙은 별도로 구현합니다.", ["class", "type-hint", "attribute"], "dataclass는 database ORM 모델과 같은 개념이 아닙니다.", "list 필드에 `items: list = []` 대신 default_factory가 필요한 이유는 무엇인가요?", None),
"python-virtual-environment": ("Python 가상환경", "프로젝트마다 Python 패키지와 버전 의존성을 분리하는 실행 환경입니다.", "프로젝트별로 도구 상자를 따로 두어 서로의 도구를 섞지 않는 것과 같습니다.", "Virtual environment는 interpreter와 site-packages 경로를 분리해 한 프로젝트의 설치·업데이트가 다른 프로젝트나 시스템 Python에 영향을 덜 주게 합니다.", "M12에서 서버 의존성을 재현 가능하게 설치하고 로컬 환경 오염을 줄입니다.", "```bash\npython -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\n```", "가상환경을 만들었다고 의존성 버전이 자동 기록되지는 않으므로 requirements 또는 lock 파일도 관리해야 합니다.", ["requirements-txt", "pyproject-toml", "python-cli"], "가상환경은 컨테이너나 운영체제 가상머신과 같은 수준의 격리가 아닙니다.", "동료가 같은 프로젝트를 실행할 때 가상환경과 의존성 목록이 함께 필요한 이유는 무엇인가요?", None),
"read-eval-print-loop": ("REPL", "입력을 읽고 실행한 뒤 결과를 출력하는 과정을 반복하는 대화형 실행 환경입니다.", "질문을 입력하면 바로 답을 보고 다음 질문을 이어 가는 계산기 같은 환경입니다.", "REPL은 Read, Eval, Print, Loop의 순서로 명령을 처리합니다. 입력 파싱과 오류 처리, 종료 명령은 일반 CLI와 별도의 상호작용 계약입니다.", "M09의 `mini-redis>`처럼 명령을 계속 받는 인터페이스를 설계하는 기준입니다.", "```text\nmini-redis> SET name codyssey\nOK\nmini-redis> GET name\ncodyssey\n```", "REPL 입력을 shell command처럼 그대로 실행하면 의도하지 않은 명령 실행 위험이 있으므로 허용 문법을 파싱해야 합니다.", ["python-cli", "loop", "input-validation"], "REPL은 단순 무한 loop가 아니라 읽기·평가·표시·오류 복구의 사용자 계약입니다.", "잘못된 REPL 명령 뒤에도 다음 프롬프트가 나와야 하는 이유는 무엇인가요?", None),
"root-cause-analysis": ("Root Cause Analysis", "문제의 표면 증상만 완화하지 않고, 재발을 만들 수 있는 근본 원인을 확인하는 조사 과정입니다.", "바닥의 물을 닦는 데서 멈추지 않고 어디서 물이 새는지 찾는 일입니다.", "Root cause analysis는 로그·측정값·변경 이력·재현 절차를 바탕으로 원인 가설을 검증하고, 증상·직접 원인·시스템 원인을 구분합니다. 하나의 사건에 단일 원인이 항상 있는 것은 아닙니다.", "M08에서 CPU 과점유나 lock 대기 문제를 임시 재시작으로 끝내지 않고 원인을 설명합니다.", "```text\n증상: 응답 지연\n증거: lock 대기 증가\n원인 가설: 획득 순서 불일치\n검증: 순서 통일 후 재현 테스트\n```", "상관관계가 있는 지표 하나만으로 원인을 확정하면 잘못된 workaround를 배포할 수 있습니다.", ["logging", "verification", "workaround"], "가장 최근에 변경한 코드가 항상 근본 원인이라는 생각은 위험합니다.", "재시작으로 장애가 사라졌다면 root cause analysis가 끝난 것인가요? 이유는 무엇인가요?", None),
"standard-library": ("Standard Library", "언어 또는 런타임과 함께 기본 제공되어 별도 설치 없이 사용할 수 있는 공식 모듈 집합입니다.", "제품을 사면 기본으로 들어 있는 도구 상자입니다.", "Python standard library에는 `json`, `pathlib`, `dataclasses` 등이 포함되지만, 설치된 모든 패키지가 표준 라이브러리는 아닙니다. 지원 Python 버전에 따라 제공 API도 달라질 수 있습니다.", "M03의 외부 패키지 금지 조건에서 어떤 모듈을 추가 설치 없이 사용할 수 있는지 판단합니다.", "```python\nfrom pathlib import Path\nfrom collections import Counter\n```", "표준 라이브러리여도 보안·성능·호환성 검토 없이 모든 문제에 적합한 것은 아닙니다.", ["numpy-pandas", "python-virtual-environment", "requirements-txt"], "pip로 설치했다는 사실은 그 패키지가 표준 라이브러리라는 뜻이 아닙니다.", "프로젝트 정책이 외부 패키지를 금지할 때 dataclasses 사용은 왜 가능한가요?", None),
"threshold": ("Threshold", "값이 정상·경고·실패 같은 다음 행동으로 바뀌는 기준점입니다.", "온도가 일정 수치를 넘으면 경보가 울리게 하는 선입니다.", "Threshold는 관찰한 값을 비교해 분기나 알림을 결정하는 도메인·운영 기준입니다. 값 자체가 아니라 측정 단위, 지속 시간, 오탐 비용과 함께 정의해야 합니다.", "M07에서 CPU나 메모리 사용량이 WARNING 기준을 넘었는지 판단합니다.", "```python\nif cpu_percent >= 80:\n    logger.warning('CPU threshold exceeded')\n```", "순간 spike 하나에 즉시 종료할지, 일정 시간 지속을 요구할지는 서비스의 위험도와 측정 간격에 따라 다릅니다.", ["cpu-usage", "logging", "verification"], "80% 같은 숫자는 보편적으로 옳은 기준이 아니라 시스템 목적에 맞춰 정해야 합니다.", "CPU 80%가 1초 발생한 경우와 10분 지속된 경우를 같은 방식으로 처리하면 어떤 문제가 있나요?", None),
"tie-handling": ("동점 처리", "여러 후보의 점수나 우선순위가 같을 때 결과를 일관되게 정하는 규칙입니다.", "결승선을 동시에 통과한 선수에게 미리 정한 판정 규칙을 적용하는 것과 같습니다.", "Tie handling은 동점 시 입력 순서, 사전순, 보조 점수, 공동 결과 같은 deterministic policy를 적용하는 과정입니다. 규칙이 없으면 실행 순서에 따라 결과가 달라질 수 있습니다.", "예비 M03의 UNDECIDED 판정에서 애매한 결과를 임의로 처리하지 않게 합니다.", "```python\n# score가 같으면 이름 오름차순으로 결정\nwinner = min(candidates, key=lambda x: (-x.score, x.name))\n```", "보조 기준을 추가하면 공정성·도메인 의미가 달라질 수 있으므로 결과 형식에 명시해야 합니다.", ["sorting-algorithm", "stable-custom-comparator", "threshold"], "동점 처리는 단순 오류 처리가 아니라 결과 계약의 일부입니다.", "입력 순서에 따라 동점 결과가 바뀌면 테스트와 사용자 신뢰에 어떤 영향이 있나요?", None),
"type-hint": ("Type Hint", "변수·매개변수·반환값에 기대하는 값의 종류를 표시하는 Python 주석형 정보입니다.", "상자에 ‘정수만 넣기’라고 라벨을 붙여 협업자가 기대값을 알게 하는 것과 같습니다.", "Python type hint는 런타임에 기본적으로 강제되지 않지만 IDE, type checker, 문서화 도구가 인터페이스 불일치를 찾아내는 데 사용합니다.", "M03에서 데이터 구조와 함수 계약을 읽기 쉽게 만들어 유지보수 가능한 설계를 돕습니다.", "```python\ndef total(values: list[int]) -> int:\n    return sum(values)\n```", "Type hint가 있다고 잘못된 외부 입력이 자동 거부되지는 않으므로 input validation은 별도로 필요합니다.", ["python-dataclass", "input-validation", "function"], "Type hint는 Java·TypeScript처럼 Python 실행을 자동으로 강하게 제한하는 문법이 아닙니다.", "`list[int]`라고 적은 함수에 문자열 목록이 들어오는 문제를 어떻게 더 일찍 찾을 수 있나요?", None),
"verification": ("Verification", "변경이나 조치가 기대한 결과를 실제 증거로 확인하는 과정입니다.", "수리 뒤에 전등이 켜지는지 다시 스위치를 눌러 보는 일입니다.", "Verification은 요구사항·측정값·테스트·로그를 사용해 결과가 만족되는지 검사합니다. 구현했다는 사실과 원하는 효과가 있었다는 사실은 다릅니다.", "M08에서 조치 전후 CPU·메모리·로그를 비교해 문제 해결을 주장할 근거를 만듭니다.", "```text\nBefore: CPU 98%\nAfter: CPU 22%, 10분 동안 재발 없음\n```", "한 번의 성공만으로 모든 환경에서 해결됐다고 결론 내리기보다 관찰 기간과 실패 조건을 정해야 합니다.", ["root-cause-analysis", "benchmark", "health-check"], "Verification은 코드 리뷰나 배포와 동의어가 아닙니다. 각각 다른 증거를 제공합니다.", "Before/After 수치를 기록하면 workaround와 근본 해결을 어떻게 구분하는 데 도움이 되나요?", None),
"watchdog": ("Watchdog", "프로세스나 시스템 상태를 주기적으로 감시하고 비정상 조건에서 알림·재시작·종료 같은 조치를 수행하는 감시자입니다.", "일정 시간 신호가 없으면 상황을 확인하는 안전 감시 장치와 같습니다.", "Watchdog은 heartbeat, timeout, 자원 사용량 같은 신호를 관찰해 정책에 따라 대응합니다. 감시 대상과 감시자 모두 실패할 수 있으므로 행동 범위와 로그가 중요합니다.", "M08에서 CPU를 과점유하는 작업을 감지하고 종료 사유를 남기는 안전 장치입니다.", "```python\nif all(sample > 90 for sample in recent_samples):\n    terminate_worker()\n```", "자동 재시작은 근본 원인을 숨기거나 반복 장애를 만들 수 있으므로 rate limit과 관찰 기록을 함께 둬야 합니다.", ["threshold", "logging", "health-check"], "Watchdog은 성능을 높이는 기능이 아니라 비정상 상태를 감지·완화하는 운영 제어입니다.", "CPU 기준을 넘은 즉시 종료하지 않고 연속 샘플을 확인하는 이유는 무엇인가요?", None),
"workaround": ("Workaround", "근본 원인을 아직 제거하지 못했을 때 영향을 줄이기 위해 임시로 적용하는 우회 조치입니다.", "누수 원인을 고치기 전 물받이를 놓아 피해를 줄이는 일입니다.", "Workaround는 서비스 복구나 위험 완화를 위해 증상을 피하는 변경이며, root cause fix와 구분해 만료 조건·부작용·후속 작업을 기록해야 합니다.", "M08 장애 상황에서 재시작·기능 제한 같은 임시 대응을 정직하게 설명합니다.", "```text\n임시 조치: 문제 작업을 1개씩만 실행\n후속 조치: lock 순서 설계 수정\n```", "임시 조치가 오래 남으면 새 장애 원인이나 운영 비용이 될 수 있으므로 제거 기준을 정해야 합니다.", ["root-cause-analysis", "verification", "deadlock"], "Workaround가 문제를 잠시 보이지 않게 했다고 근본 원인이 사라진 것은 아닙니다.", "재시작을 workaround로 적용했다면 어떤 증거와 후속 작업을 남겨야 하나요?", None),
"yield": ("yield", "Python generator가 값을 하나 내보내고 실행 상태를 다음 호출까지 보존하게 하는 키워드입니다.", "책갈피를 끼워 둔 채 한 페이지를 건네고, 다음에 같은 자리에서 다시 읽는 것과 같습니다.", "`yield`가 있는 함수는 호출 즉시 본문을 모두 실행하지 않고 generator object를 반환합니다. iteration이 진행될 때마다 값과 지역 상태를 보존·재개합니다.", "M03에서 큰 데이터를 지연 처리하는 generator 구현의 핵심 문법입니다.", "```python\ndef count_up():\n    yield 1\n    yield 2\n```", "yield를 쓰는 함수의 반환값·예외·종료 처리 방식은 일반 return 함수와 다르므로 호출자가 iterator로 소비해야 합니다.", ["generator", "iterator", "function"], "yield는 값을 출력하는 print가 아니며, generator를 만들었다고 값이 바로 계산되는 것도 아닙니다.", "count_up()을 호출한 직후와 next(count_up())를 호출한 뒤에는 무엇이 다른가요?", None),
"cpu-architecture": ("CPU Architecture", "프로그램의 명령 형식과 바이너리 호환성을 결정하는 CPU 계열과 실행 환경의 규약입니다.", "같은 설명서라도 서로 다른 규격의 부품에는 바로 맞지 않는 것과 같습니다.", "CPU architecture는 x86_64, ARM64처럼 instruction set과 ABI 특성을 포함합니다. 운영체제가 같아도 다른 architecture용으로 빌드된 바이너리는 직접 실행되지 않을 수 있습니다.", "M07에서 실행 파일·컨테이너 이미지가 현재 서버의 x86/arm64 환경과 맞는지 확인합니다.", "```bash\nuname -m  # 예: arm64 또는 x86_64\n```", "32/64비트, 운영체제, CPU architecture는 관련 있지만 같은 분류가 아니므로 오류 메시지의 실제 호환 축을 확인해야 합니다.", ["docker-image", "docker-container", "linux"], "ARM64가 항상 x86_64보다 빠르거나 호환된다는 일반화는 맞지 않습니다.", "ARM64 서버에서 x86_64 전용 이미지를 실행할 때 어떤 선택지가 있나요?", None),
"stack-trace": ("Stack Trace", "오류가 발생한 지점까지 어떤 함수 호출을 거쳐 왔는지 보여 주는 호출 기록입니다.", "사고 현장까지 지나온 길을 역순으로 적은 기록과 같습니다.", "Stack trace는 예외 발생 시 call stack의 함수 이름·파일·줄 번호를 표시해 오류 위치와 호출 경로를 추적하게 합니다. 환경에 따라 경로나 내부 정보가 포함될 수 있습니다.", "M03에서 서버 오류의 원인을 조사하되, 사용자 응답에 내부 stack trace를 노출하지 않는 기준입니다.", "```text\nFile service.py, line 12, in create_user\n  validate(payload)\nValueError: invalid email\n```", "운영 환경의 stack trace는 내부 경로·라이브러리 정보를 드러낼 수 있으므로 로그에는 접근 제어를 하고 응답은 안전한 오류로 바꿉니다.", ["call-stack", "exception-handling", "logging"], "Stack trace는 오류 원인 그 자체가 아니라 오류까지의 호출 경로라는 점을 구분해야 합니다.", "사용자에게 원본 stack trace 대신 일반 오류 메시지를 주어야 하는 이유는 무엇인가요?", None),
"big-o-notation": ("빅오 표기법", "입력 크기가 커질 때 알고리즘의 시간 또는 공간 사용량이 어떻게 증가하는지 상한의 형태로 나타내는 표기입니다.", "손님 수가 늘 때 계산대 일이 얼마나 빠르게 늘어나는지 보는 성장률 표지판입니다.", "Big-O는 상수 계수와 작은 입력의 세부 비용보다 n이 커질 때 지배적인 증가 항을 비교합니다. 실제 실행 시간은 하드웨어·입력 분포·구현 상수에도 영향을 받습니다.", "예비 M03에서 O(N²) 같은 표기를 읽고 데이터 규모에 맞는 구현을 고릅니다.", "```text\nfor a in values:\n  for b in values: ...  # O(N²)\n```", "Big-O가 더 낮아도 작은 입력에서는 단순 구현이 더 빠를 수 있으므로 측정과 요구 규모를 함께 봐야 합니다.", ["time-complexity", "benchmark", "memoization"], "Big-O는 프로그램의 실제 초 단위를 보장하거나 코드 품질 전체를 점수화하는 표기가 아닙니다.", "O(N)과 O(N²)의 차이가 입력 10개와 1,000,000개에서 왜 크게 달라지나요?", None),
"memoization": ("Memoization", "같은 입력의 함수 결과를 저장해 다음 호출에서 계산을 반복하지 않는 최적화 기법입니다.", "이미 푼 계산 문제의 답을 메모해 같은 문제를 다시 풀지 않는 방식입니다.", "Memoization은 함수 입력을 cache key로 사용해 이전 결과를 재사용합니다. 순수 함수와 제한된 입력 공간에 적합하며, key 생성·메모리·무효화 비용이 있습니다.", "M02에서 useMemo·useCallback·React.memo를 결과 재사용이라는 상위 개념으로 비교합니다.", "```python\nfrom functools import lru_cache\n@lru_cache\ndef fib(n):\n    return n if n < 2 else fib(n-1) + fib(n-2)\n```", "외부 상태에 의존하거나 매번 달라지는 함수 결과를 무조건 memoize하면 오래된 값을 재사용할 수 있습니다.", ["cache", "least-recently-used", "react-memo"], "Memoization은 모든 함수를 자동으로 빠르게 만드는 기능이 아니며, cache 관리 비용이 있습니다.", "현재 시간에 의존하는 함수를 memoize하면 왜 잘못된 결과가 나올 수 있나요?", None),
"mutex": ("Mutex", "한 시점에 하나의 실행 흐름만 임계 구역에 들어가게 하는 mutual exclusion lock입니다.", "한 장짜리 출입증을 가진 사람만 방에 들어갈 수 있게 하는 장치입니다.", "Mutex는 공유 데이터를 보호하기 위한 lock의 대표 구현입니다. 획득한 주체가 해제해야 하는 규칙과 운영체제·언어 런타임의 스케줄링 특성을 가질 수 있습니다.", "M08에서 lock을 구체적으로 구현할 때 race condition과 deadlock의 관계를 설명합니다.", "```python\nmutex.acquire()\ntry:\n    update_shared_state()\nfinally:\n    mutex.release()\n```", "Mutex가 있다고 복합 연산 전체가 자동 원자적이 되는 것은 아니며, 보호할 임계 구역을 정확히 정해야 합니다.", ["lock", "deadlock", "race-condition"], "Mutex와 semaphore는 모두 동기화 도구지만 허용 동시 접근 수와 사용 목적이 다릅니다.", "finally에서 mutex를 해제하지 않으면 어떤 문제가 생기나요?", None),
"race-condition": ("Race Condition", "여러 실행 흐름의 실행 순서에 따라 공유 상태의 결과가 달라지는 오류 조건입니다.", "두 사람이 같은 마지막 좌석을 동시에 예약하려 해 결과가 순서에 따라 달라지는 상황입니다.", "Race condition은 읽기·수정·쓰기 같은 여러 단계가 원자적으로 보호되지 않아 interleaving에 따라 데이터가 손실되거나 불일치할 때 발생합니다.", "M08에서 deadlock과 달리 작업은 진행될 수 있지만 결과가 틀릴 수 있는 동시성 문제를 구분합니다.", "```python\n# 둘 다 balance=0을 읽고 1을 써서 기대값 2 대신 1이 될 수 있다\nbalance += 1\n```", "Lock이 유일한 해결책은 아닙니다. atomic operation, message passing, DB transaction 등 상황에 맞는 경계를 선택할 수 있습니다.", ["lock", "mutex", "deadlock", "transaction"], "Race condition은 항상 재현되는 버그가 아니어서 테스트 한 번 통과했다고 없다고 단정하기 어렵습니다.", "두 요청이 같은 재고 1개를 동시에 구매할 때 어떤 읽기·쓰기 순서가 문제를 만들 수 있나요?", None),
"separation-of-concerns": ("Separation of Concerns", "서로 다른 변경 이유를 가진 책임을 분리해 각 부분이 한 가지 관심사에 집중하게 하는 설계 원칙입니다.", "주문 접수, 요리, 배달을 한 사람이 뒤섞어 하지 않고 역할을 나누는 방식입니다.", "Separation of concerns는 UI, 검증, 비즈니스 규칙, 저장소 접근처럼 독립적으로 변할 수 있는 관심사를 분리합니다. 파일을 많이 쪼개는 것보다 의존 방향과 책임 경계가 중요합니다.", "M03·M12에서 검증·로깅·도메인 처리·DB 접근을 나누어 변경과 테스트 범위를 줄입니다.", "```text\nController: 요청 해석\nService: 업무 규칙\nRepository: 저장소 접근\n```", "관심사를 지나치게 잘게 나누면 흐름을 따라가기 어렵고 간접 호출만 늘 수 있으므로 함께 바뀌는 코드는 응집시켜야 합니다.", ["layered-architecture", "decorator", "dependency-injection"], "분리는 코드 줄 수를 균등하게 나누는 규칙이 아니라 변경 이유를 다루는 원칙입니다.", "이메일 형식 검증을 DB repository 안에 두면 어떤 변경이 어려워질까요?", None),
"commit-subcommand": ("commit 명령", "Git에서 staging area의 변경을 하나의 이력 단위로 기록하는 `git commit` 하위 명령입니다.", "검토한 변경 묶음에 날짜와 설명을 붙여 이력 장부에 확정하는 동작입니다.", "`git commit`은 index에 올린 스냅샷을 새 commit object로 만들고 부모 commit을 연결합니다. 작업 디렉터리의 모든 변경을 자동으로 포함하지는 않습니다.", "M06에서 생성한 변경을 의미 있는 제목과 함께 협업 가능한 이력으로 남깁니다.", "```bash\ngit add report.md\ngit commit -m 'docs: add report'\n```", "`git commit -a`는 추적 중인 수정·삭제를 stage하지만 새 untracked 파일까지 추가하지는 않습니다.", ["staging-area-git-add", "commit", "commit-message-convention"], None, None, None),
"main-py": ("main.py", "Python 프로그램의 진입점으로 자주 쓰이는 파일 이름이며, 프로젝트가 정한 실행 시작 위치입니다.", "책의 첫 장처럼 프로그램을 어디서 시작할지 알려 주는 약속된 표지입니다.", "`main.py`는 Python 언어가 강제하는 특별 파일명은 아니지만 과제·프로젝트에서 `python main.py` 실행 계약으로 사용될 수 있습니다.", "예비 M03에서 제출 산출물의 파일명과 실행 경로를 요구사항대로 맞춥니다.", "```bash\npython main.py\n```", "패키지 프로젝트에서는 `python -m package`가 진입점일 수 있으므로 파일명 관례와 실제 실행 명령을 혼동하지 않습니다.", ["python-cli", "pyproject-toml"], None, None, None),
"requirements-txt": ("requirements.txt", "Python 프로젝트가 설치에 필요한 패키지와 버전을 나열하는 관례적 의존성 파일입니다.", "다른 사람이 같은 도구 상자를 준비할 수 있게 적어 둔 구매 목록입니다.", "`requirements.txt`는 보통 pip가 읽는 requirement specifier 목록이며, 직접 의존성만 쓸지 전이 의존성까지 고정할지는 프로젝트 재현성 정책에 따라 정합니다.", "M12에서 서버 실행에 필요한 패키지를 동료·배포 환경에서 같은 방식으로 설치하게 합니다.", "```text\nfastapi==0.115.0\nuvicorn[standard]==0.30.0\n```", "파일이 있다고 설치 환경이 완전히 같아지는 것은 아니며 Python 버전·OS·비밀 설정도 별도로 관리해야 합니다.", ["python-virtual-environment", "pyproject-toml", "standard-library"], None, None, None),
"attribute": ("속성", "객체나 클래스에 붙어 그 상태 또는 메타데이터를 나타내는 이름 붙은 값입니다.", "학생 카드에 이름·학번 칸이 붙어 있는 것처럼 객체가 가진 정보 칸입니다.", "Python에서 attribute는 `object.name` 형태로 접근하며 인스턴스 attribute, class attribute, property처럼 저장·조회 규칙이 다를 수 있습니다.", "예비 M02에서 클래스가 보유하는 데이터를 메서드와 구분해 모델링합니다.", "```python\nuser.name = 'Mina'\n```", "class attribute를 가변 값으로 두면 모든 인스턴스가 공유할 수 있으므로 인스턴스별 상태인지 구분해야 합니다.", ["class", "method", "python-dataclass"], None, None, None),
"publish-subscribe": ("Publish/Subscribe", "발행자가 메시지를 주제에 보내고 구독자가 그 주제를 받아 처리하는 비동기 메시징 패턴입니다.", "신문사가 기사를 발행하면 구독자가 각자 받아보는 구조와 비슷합니다.", "Pub/Sub는 producer와 consumer를 직접 결합하지 않고 broker 또는 topic을 통해 메시지를 전달합니다. 전달 보장, 순서, 중복 처리 방식은 시스템마다 다릅니다.", "M09 보너스 기능에서 이벤트 기반 기능을 확장할 때 생산자와 소비자의 결합을 줄입니다.", "```text\npublish('user.created', payload)\nsubscribe('user.created', send_welcome_email)\n```", "구독자가 메시지를 반드시 한 번만 받는다는 보장은 기본 전제가 아니므로 idempotency와 재시도 정책을 정해야 합니다.", ["queue", "asynchronous-programming", "event-loop"], None, None, None),
"pyproject-toml": ("pyproject.toml", "Python 프로젝트의 빌드 도구·패키지 메타데이터·의존성을 선언할 수 있는 표준 설정 파일입니다.", "프로젝트를 만들고 배포하는 데 필요한 규칙을 한곳에 적은 설계표입니다.", "`pyproject.toml`은 PEP 518 기반의 TOML 파일로 build-system을 정의하며 도구에 따라 project metadata와 dependency도 담습니다. 모든 도구가 같은 키를 해석하는 것은 아닙니다.", "M12에서 requirements.txt 외의 의존성·도구 설정 방식을 이해합니다.", "```toml\n[project]\nname = 'my-api'\ndependencies = ['fastapi']\n```", "pyproject.toml만 추가했다고 pip 설치 방식이나 lock 파일 정책이 자동으로 통일되지는 않습니다.", ["requirements-txt", "python-virtual-environment"], None, None, None),
}


def render(term_id: str, tier: str, values: tuple) -> str:
    title, summary, easy, technical, mission, example, boundary, related, misconception, question, works = values
    parts = [f"# {title}", "", "## 한 줄 설명", "", summary, "", "## 쉽게 설명하면", "", easy, "", "## 정확한 설명", "", technical]
    if tier == "A":
        parts += ["", "## 동작 원리", "", works]
    parts += ["", "## 이 미션에서는 왜 필요한가", "", mission, "", "## 코드 예", "", example]
    if tier in {"A", "B"}:
        parts += ["", "## 주의할 점 / 경계 조건", "", boundary]
    if related:
        parts += ["", "## 관련 용어", ""] + [f"- `{item}`" for item in related]
    if tier in {"A", "B"}:
        parts += ["", "## 흔한 오해", "", misconception, "", "## 동료평가 질문", "", question]
    return "\n".join(parts) + "\n"


def main() -> None:
    plan = json.loads(PLAN.read_text(encoding="utf-8"))
    batch = next(item for item in plan["implementation_batches"] if item["id"] == BATCH_ID)
    item_by_id = {item["term_id"]: item for item in plan["items"]}
    target_ids = batch["term_ids"]
    assert len(target_ids) == 44 and set(target_ids) == set(CONTENT), "S7-B01 source-of-truth mismatch"
    TERMS.mkdir(exist_ok=True)
    for term_id in target_ids:
        item = item_by_id[term_id]
        assert item["content_state"] == "missing", f"{term_id} is not a missing-content item"
        (TERMS / f"{term_id}.md").write_text(render(term_id, item["tier"], CONTENT[term_id]), encoding="utf-8")
    master = json.loads(MASTER.read_text(encoding="utf-8"))
    for term in master["terms"]:
        if term["id"] in target_ids:
            term["content_status"] = "drafted"
    MASTER.write_text(json.dumps(master, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(target_ids)} S7-B01 term files from {BATCH_ID}.")


if __name__ == "__main__":
    main()
