let terms=[],book,checks=[],tab='requirements';const app=document.querySelector('#app');const aliases={'local-storage':['localstorage','local storage','로컬스토리지','로컬 스토리지'],'intersection-observer-api':['intersection observer','intersectionobserver','인터섹션 옵저버','인터섹션옵저버'],'github-api':['깃허브 api'],'github-pages':['깃허브 페이지스'],'add-event-listener':['이벤트 리스너']};const context={'dom':['브라우저가 HTML 문서를 JavaScript가 조작할 수 있는 객체 구조로 표현한 것.','메뉴·다크모드·필터처럼 사용자 행동 뒤 화면 요소를 바꿀 때 사용합니다.','HTML 파일을 다시 쓰지 않았는데 클릭 뒤 화면이 바뀌는 이유는 무엇인가요?'],'local-storage':['브라우저에 값을 저장해 새로고침 뒤에도 유지할 수 있는 저장 공간.','M01에서 다크모드 선택 상태를 유지합니다.','변수에만 상태를 저장하면 새로고침 후 왜 사라질까요?'],'intersection-observer-api':['viewport에 요소가 들어왔는지 관찰하는 브라우저 API.','M01에서 섹션이 보이는 시점에 스크롤 애니메이션을 시작합니다.','scroll 이벤트마다 위치를 계산하는 방식과의 차이는 무엇인가요?']};
const norm=s=>s.toLowerCase().trim().replace(/[\s_-]+/g,'').replace(/[./]/g,'');const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const term=id=>terms.find(t=>t.id===id);const name=id=>term(id)?.termKo||id;
Promise.all([fetch('glossary.json').then(r=>r.json()),fetch('openbook-main-m01.json').then(r=>r.json())]).then(([t,b])=>{terms=t;book=b;chrome.storage.local.get(['m01Checks','openbookSearch'],x=>{checks=x.m01Checks||[];if(x.openbookSearch){tab='search';search(x.openbookSearch);chrome.storage.local.remove('openbookSearch')}else render()})});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});function select(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}function save(){chrome.storage.local.set({m01Checks:checks})}function render(){select();if(tab==='requirements')requirements();else if(tab==='search')search('');else checklist()}
function bind(){app.querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>{checks=e.checked?[...checks,e.dataset.check]:checks.filter(x=>x!==e.dataset.check);save();render()});app.querySelectorAll('[data-term]').forEach(e=>e.onclick=x=>{x.preventDefault();tab='search';search(e.dataset.term)})}
function requirements(){const done=checks.length;app.innerHTML=`<div class="progress"><b>${done} / ${book.requirements.length} 확인</b><i><span style="width:${done/book.requirements.length*100}%"></span></i></div><div class="quick">${book.quick_terms.map(id=>`<a href="#" data-term="${id}">${name(id)}</a>`).join('')}</div>`+book.requirements.map((r,i)=>`<article class="req ${checks.includes(r.id)?'done':''}"><label><input type="checkbox" data-check="${r.id}" ${checks.includes(r.id)?'checked':''}><b>${String(i+1).padStart(2,'0')}. ${r.title}</b></label><p>${r.requirement_summary}</p><details><summary>확인 ${r.demo_checks.length}개 · 질문 ${r.peer_questions.length}개</summary><b>화면에서 확인</b><p>${r.demo_checks.join('<br>• ')}</p><b>코드에서 확인</b><p>${r.code_checks.join('<br>• ')}</p><b>동료평가 질문</b><p>${r.peer_questions[0]}</p><div class="quick">${r.term_refs.map(id=>`<a href="#" data-term="${id}">${name(id)}</a>`).join('')}</div></details></article>`).join('');bind()}
function find(q){const n=norm(q);return terms.map(t=>{const vals=[t.termKo,t.termEn,...t.aliases,...(aliases[t.id]||[])];const exact=vals.some(v=>v.toLowerCase()===q.toLowerCase())?0:vals.some(v=>norm(v)===n)?1:vals.some(v=>norm(v).startsWith(n))?2:vals.some(v=>norm(v).includes(n))?3:9;return{t,exact,m01:t.missionRefs.some(r=>r.course==='main'&&r.mission==='M01')}}).filter(x=>x.exact<9).sort((a,b)=>a.exact-b.exact||Number(b.m01)-Number(a.m01)).slice(0,12)}
function search(initial){select();app.innerHTML=`<label class="sr" for="q">용어 검색</label><input id="q" value="${esc(initial)}" placeholder="550개 기술용어를 검색하세요"><p id="hint">예: localStorage, DOM, fetch, Intersection Observer, GitHub API</p><div id="results"></div>`;const q=document.querySelector('#q');q.oninput=()=>show(q.value);if(initial)show(initial);function show(v){const out=document.querySelector('#results');if(!v.trim()){out.innerHTML='';return}const r=find(v);out.innerHTML=r.length?r.map(({t,m01})=>{const c=context[t.id];return `<article class="result"><b>${t.termKo}</b><small>${t.termEn}</small><p>${c?c[0]:(t.summary||'미션에서 확인된 기술용어입니다.')}</p>${c?`<p><em>M01에서는</em> ${c[1]}</p><p><b>질문</b> ${c[2]}</p>`:''}<em>${m01?'본과정 M01 관련 용어':'전체 사전 용어'}</em></article>`}).join(''):`<article class="unknown"><b>${esc(v)}</b><p>아직 코디세이 오픈북 사전에 없는 용어입니다.</p><button id="websearch">웹에서 검색하기</button></article>`;if(!r.length)document.querySelector('#websearch').onclick=()=>chrome.search.query({text:v,disposition:'NEW_TAB'});}}
function checklist(){app.innerHTML='<h2>평가 체크</h2>'+book.requirements.map(r=>`<label class="check"><input type="checkbox" data-check="${r.id}" ${checks.includes(r.id)?'checked':''}> ${r.title}</label>`).join('')+'<button class="reset" id="reset">평가 체크 초기화</button>';document.querySelector('#reset').onclick=()=>{checks=[];save();checklist()};bind()}
